from typing import Any
import app.ui.widgets.actions.control_actions as control_actions

COMMON_LAYOUT_DATA: Any = {
    "Face Restorer": {
        "FaceRestorerEnableToggle": {
            "level": 1,
            "label": "Enable Face Restorer",
            "default": False,
            "help": "Enable the use of a face restoration model to improve the quality of the face after swapping.",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnableToggle"],
        },
        "FaceRestorerTypeSelection": {
            "level": 2,
            "label": "Restorer Type",
            "options": [
                "GFPGAN-v1.4",
                "GFPGAN-1024",
                "CodeFormer",
                "GPEN-256",
                "GPEN-512",
                "GPEN-1024",
                "GPEN-2048",
                "RestoreFormer++",
                "VQFR-v2",
            ],
            "default": "GFPGAN-v1.4",
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Select the model type for face restoration.",
            "exec_function": control_actions.handle_model_selection_change,
            "exec_function_args": ["FaceRestorerTypeSelection"],
        },
        "FaceRestorerDetTypeSelection": {
            "level": 2,
            "label": "Alignment",
            "options": ["Original", "Blend", "Reference"],
            "default": "Original",
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Select the alignment method for restoring the face to its original or blended position.",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnable2Toggle"],
        },
        "FaceFidelityWeightDecimalSlider": {
            "level": 2,
            "label": "Fidelity Weight",
            "min_value": "0.0",
            "max_value": "1.0",
            "default": "0.9",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Adjust the fidelity weight to control how closely the restoration preserves the original face details (For CodeFormer and VQFR-v2 only).",
        },
        "FaceRestorerBlendSlider": {
            "level": 2,
            "label": "Blend",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Control the blend ratio between the restored face and the swapped face.",
        },
        "FaceRestorerAutoEnableToggle": {
            "level": 2,
            "label": "Auto Restore",
            "default": False,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "Auto Adjust Restorer Blend Amount",
        },
        "FaceRestorerAutoSharpAdjustSlider": {
            "level": 3,
            "label": "Adjust Sharpness",
            "min_value": "-60",
            "max_value": "60",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle",
            "requiredToggleValue": True,
            "help": "Adjust sharp calc. mostly needed for over 0, which makes the swap sharper. depends on swap model, restorer model, resolution, face size,...",
        },
        "FaceRestorerAutoMaskEnableToggle": {
            "level": 3,
            "label": "Sharpness Mask",
            "default": False,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle",
            "requiredToggleValue": True,
            "help": "Auto Adjust Restorer Blend Amount with sharpness Map",
        },
        "FaceRestorerAutoSharpMaskAdjustDecimalSlider": {
            "level": 4,
            "label": "Mask Adjust",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle & FaceRestorerAutoMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "Adjust Min/Max Blend value change from base auto Blend value",
        },
        "FaceRestorerEnable2Toggle": {
            "level": 1,
            "label": "Enable Face Restorer 2",
            "default": False,
            "help": "Enable the use of a face restoration model to improve the quality of the face after swapping.",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnable2Toggle"],
        },
        "FaceRestorerEnable2EndToggle": {
            "level": 2,
            "label": "Apply at End",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Apply the second restorer at end of pipeline (after Face Editor to compensate the sharpness loss, befor final-blur and jpeg/mpeg-Compression. when disabled apply directly after first restorer like originaly.",
        },
        "FaceRestorerType2Selection": {
            "level": 2,
            "label": "Restorer Type",
            "options": [
                "GFPGAN-v1.4",
                "GFPGAN-1024",
                "CodeFormer",
                "GPEN-256",
                "GPEN-512",
                "GPEN-1024",
                "GPEN-2048",
                "RestoreFormer++",
                "VQFR-v2",
            ],
            "default": "GFPGAN-v1.4",
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Select the model type for face restoration.",
            "exec_function": control_actions.handle_model_selection_change,
            "exec_function_args": ["FaceRestorerType2Selection"],
        },
        "FaceRestorerDetType2Selection": {
            "level": 2,
            "label": "Alignment",
            "options": ["Original", "Blend", "Reference"],
            "default": "Original",
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Select the alignment method for restoring the face to its original or blended position.",
        },
        "FaceFidelityWeight2DecimalSlider": {
            "level": 2,
            "label": "Fidelity Weight",
            "min_value": "0.0",
            "max_value": "1.0",
            "default": "0.9",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Adjust the fidelity weight to control how closely the restoration preserves the original face details.",
        },
        "FaceRestorerBlend2Slider": {
            "level": 2,
            "label": "Blend",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Control the blend ratio between the restored face and the swapped face.",
        },
        "FaceRestorerAutoEnable2Toggle": {
            "level": 2,
            "label": "Auto Restore2",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Auto Adjust Restorer2 Blend Amount",
        },
        "FaceRestorerAutoSharpAdjust2Slider": {
            "level": 3,
            "label": "adjust sharpness",
            "min_value": "-60",
            "max_value": "60",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Adjust sharp calc. mostly needed for over 0, which makes the swap sharper. depends on swap model, restorer model, resolution, face size,...",
        },
        "FaceRestorerAutoMask2EnableToggle": {
            "level": 3,
            "label": "Sharpness Mask",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle",
            "requiredToggleValue": True,
            "help": "Auto Adjust Restorer Blend Amount with sharpness Map",
        },
        "FaceRestorerAutoSharpMask2AdjustDecimalSlider": {
            "level": 4,
            "label": "Mask Adjust",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle & FaceRestorerAutoMask2EnableToggle",
            "requiredToggleValue": True,
            "help": "Adjust Min/Max Blend value change from base auto Blend value",
        },
    },
    "Face expressions": {
        "FaceExpressionBeforeTypeSelection": {
            "level": 1,
            "label": "Pipeline Position",
            "options": ["Beginning", "After First Restorer", "After Second Restorer"],
            "default": "Beginning",
            "help": "Select the Face Expression Restorer Editor position in the pipeline.",
        },
        "FaceExpressionEnableBothToggle": {
            "level": 1,
            "label": "Enable Face Expression Restorer",
            "default": False,
            "help": "Enabled the use of the LivePortrait face expression model to restore facial expressions after swapping.",
            "exec_function": control_actions.handle_face_expression_toggle_change,
            "exec_function_args": ["FaceExpressionEnableBothToggle"],
        },
        "FaceExpressionModeSelection": {
            "level": 2,
            "label": "Mode",
            "options": ["Simple", "Advanced"],
            "default": "Simple",
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "Choose 'Advanced' for fine-tuning and retargeting options.",
        },
        "FaceExpressionCropScaleBothDecimalSlider": {
            "level": 2,
            "label": "Crop Scale",
            "min_value": "1.7",
            "max_value": "3.0",
            "default": "2.3",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "Changes swap crop scale. Increase the value to capture the face more distantly.",
        },
        "FaceExpressionVYRatioBothDecimalSlider": {
            "level": 2,
            "label": "VY Ratio",
            "min_value": "-0.125",
            "max_value": "-0.100",
            "default": "-0.125",
            "step": 0.001,
            "decimals": 3,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "Changes the vy ratio for crop scale. Increase the value to capture the face more distantly.",
        },
        "FaceExpressionNeutralDecimalSlider": {
            "level": 2,
            "label": "Neutral Factor",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "0.30",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "Percentage of expression to add. Swapped Face already has some expression due to swap, adding complet expression is not recommended and slider should be lower than 1.0",
        },
        # --- SIMPLE MODE WIDGETS (RESTORING OLD FUNCTIONALITY) ---
        "FaceExpressionFriendlyFactorDecimalSlider": {
            "level": 3,
            "label": "Expression Factor",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Simple",
            "help": "Control the expression similarity between the driving face and the swapped face.",
        },
        "FaceExpressionAnimationRegionSelection": {
            "level": 3,
            "label": "Animation Region",
            "options": ["all", "eyes", "lips"],
            "default": "all",
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Simple",
            "help": "The facial region involved in the restoration process.",
        },
        "FaceExpressionNormalizeLipsEnableToggle": {
            "level": 3,
            "label": "Normalize Lips",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Simple",
            "help": "Normalize the lips during the facial restoration process.",
        },
        "FaceExpressionNormalizeLipsThresholdDecimalSlider": {
            "level": 4,
            "label": "Normalize Lips Threshold",
            "min_value": "0.10",
            "max_value": "1.00",
            "default": "0.03",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeLipsEnableToggle & FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Simple",
            "help": "Threshold value for Normalize Lips.",
        },
        # --- ADVANCED MODE WIDGETS (CURRENT LAYOUT) ---
        "FaceExpressionMicroExpressionBoostDecimalSlider": {
            "level": 3,
            "label": "Micro-Expression Boost",
            "min_value": "0.80",
            "max_value": "1.50",
            "default": "1.00",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Amplifies movements when using Relative Motion. Default is 1.00.",
        },
        "FaceExpressionEyesToggle": {
            "level": 3,
            "label": "Restore The Eyes",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Activate the eyes face expression restorer",
        },
        "FaceExpressionStableGazeEyesToggle": {
            "level": 4,
            "label": "Relative Lids + Retargeted Gaze",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Combines the eye motion from Relative Position with the gaze correction from Retargeting Eyes.\n\n- eyelid motion is biased toward Relative Position\n- gaze direction is biased toward Retargeting Eyes\n\nEnabling this mode also turns on Relative Position and Retargeting Eyes.",
            "exec_function": control_actions.handle_face_expression_eye_blend_toggle,
            "exec_function_args": ["FaceExpressionStableGazeEyesToggle"],
        },
        "FaceExpressionRelativeEyesToggle": {
            "level": 4,
            "label": "Relative Position",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Makes the animation relative to the initial pose of the source image. Can be better for a more natural look.",
            "exec_function": control_actions.handle_face_expression_eye_blend_toggle,
            "exec_function_args": ["FaceExpressionRelativeEyesToggle"],
        },
        "FaceExpressionFriendlyFactorEyesDecimalSlider": {
            "level": 4,
            "label": "Eyes Expression Factor",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Control the expression similarity between the driving face and the swapped face of the eyes.",
        },
        "FaceExpressionRetargetingEyesBothEnableToggle": {
            "level": 4,
            "label": "Retargeting Eyes",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Adjusting or redirecting the gaze or movement of the eyes during the facial restoration process.",
            "exec_function": control_actions.handle_face_expression_eye_blend_toggle,
            "exec_function_args": ["FaceExpressionRetargetingEyesBothEnableToggle"],
        },
        "FaceExpressionRetargetingEyesMultiplierBothDecimalSlider": {
            "level": 5,
            "label": "Eyes Multiplier",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionRetargetingEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Multiplier value for Retargeting Eyes.",
        },
        "FaceExpressionNormalizeEyesBothEnableToggle": {
            "level": 5,
            "label": "Normalize Eyes",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Normalize the Eyes during the facial restoration process.",
        },
        "FaceExpressionNormalizeEyesThresholdBothDecimalSlider": {
            "level": 6,
            "label": "Eyes Threshold",
            "min_value": "0.10",
            "max_value": "1.00",
            "default": "0.40",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Threshold for the eye open ratio, it will dictate at wich open/close ratio it uses the modified faceutil function.",
        },
        "FaceExpressionNormalizeEyesMaxBothDecimalSlider": {
            "level": 6,
            "label": "Max Open Ratio",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "0.45",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Max eye open ratio that the target will have (<0.5 is best).",
        },
        "FaceExpressionBrowsToggle": {
            "level": 3,
            "label": "Restore Brows",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Activate the restoration of eyebrows.",
        },
        "FaceExpressionRelativeBrowsToggle": {
            "level": 4,
            "label": "Relative Position",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionBrowsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Makes the animation relative to the initial pose of the source image. Reduces geometric distortions on face shape.",
        },
        "FaceExpressionFriendlyFactorBrowsDecimalSlider": {
            "level": 4,
            "label": "Brows Expression Factor",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionBrowsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Control the expression intensity for eyebrows.",
        },
        "FaceExpressionLipsToggle": {
            "level": 3,
            "label": "Restore The Lips",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Activate the lips face expression restorer",
        },
        "FaceExpressionRelativeLipsToggle": {
            "level": 4,
            "label": "Relative Position",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Makes the animation relative to the initial pose of the source image. Can be better for a more natural look.",
        },
        "FaceExpressionFriendlyFactorLipsDecimalSlider": {
            "level": 4,
            "label": "Lips Expression Factor",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Control the expression similarity between the driving face and the swapped face of the lips.",
        },
        "FaceExpressionRetargetingLipsBothEnableToggle": {
            "level": 4,
            "label": "Retargeting Lips",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Adjusting or modifying the position, shape, or movement of the lips during the facial restoration process.",
        },
        "FaceExpressionRetargetingLipsMultiplierBothDecimalSlider": {
            "level": 5,
            "label": "Lips Multiplier",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionRetargetingLipsBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Multiplier value for Retargeting Lips.",
        },
        "FaceExpressionNormalizeLipsBothEnableToggle": {
            "level": 4,
            "label": "Normalize Lips",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Normalize the lips during the facial restoration process.",
        },
        "FaceExpressionNormalizeLipsThresholdBothDecimalSlider": {
            "level": 5,
            "label": "Lips Threshold",
            "min_value": "0.00",
            "max_value": "0.20",
            "default": "0.03",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeLipsBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Threshold value for Normalize Lips.",
        },
        "FaceExpressionGeneralToggle": {
            "level": 3,
            "label": "Restore General Face Features",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Activate the restoration of general expressions. (Comment or Uncomment face parts in frame_edits.py for more control)",
        },
        "FaceExpressionRelativeGeneralToggle": {
            "level": 4,
            "label": "Relative Position",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Makes the animation relative to the initial pose of the source image. Reduces geometric distortions on face shape.",
        },
        "FaceExpressionGeneralNoseToggle": {
            "level": 4,
            "label": "Include Nose",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Adds Nose Indices to the General Expression.",
        },
        "FaceExpressionGeneralJawToggle": {
            "level": 4,
            "label": "Include Jaw",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Adds Jaw Indices to the General Expression.",
        },
        "FaceExpressionGeneralCheekToggle": {
            "level": 4,
            "label": "Include Cheek",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Adds Cheek Indices to the General Expression.",
        },
        "FaceExpressionGeneralContourToggle": {
            "level": 4,
            "label": "Include Contour",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Adds Contour Indices to the General Expression.",
        },
        "FaceExpressionGeneralHeadToggle": {
            "level": 4,
            "label": "Include Head top",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Adds Head Top Indices to the General Expression.",
        },
        "FaceExpressionFriendlyFactorGeneralDecimalSlider": {
            "level": 4,
            "label": "General Expression Factor",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "Control the expression intensity for General Features.",
        },
        "AutoMouthExpressionEnableToggle": {
            "level": 1,
            "label": "Enable Auto Mouth Expression",
            "default": False,
            "exec_function": control_actions.handle_auto_mouth_toggle,
            "exec_function_args": [],
            "help": (
                "Triggers lip expression or face-parser mouth masks automatically when "
                "mouth action is detected. In 'Expression Restorer' mode, takes "
                "precedence over the face expression restorer's lip settings while "
                "preserving your eye configuration. Deactivating auto mouth restores "
                "normal face expression restorer behaviour for lips."
            ),
        },
        "AutoMouthRestoreModeSelection": {
            "level": 2,
            "label": "Trigger Mode",
            "options": ["Expression Restorer", "Face Parser Only"],
            "default": "Expression Restorer",
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "help": (
                "'Expression Restorer': overrides the face expression restorer lip "
                "settings when mouth is detected — preserves your eye/brow/general "
                "restorer settings, updates mouth position. Slower (runs LivePortrait). "
                "'Face Parser Only': applies face-parser mouth dilation masks only, "
                "no expression transfer — faster, similar to xseg mouth."
            ),
        },
        "AutoMouthOpenThresholdDecimalSlider": {
            "level": 2,
            "label": "Confidence Threshold",
            "min_value": "0.01",
            "max_value": "0.99",
            "default": "0.50",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "enable_refresh_frame": False,
            "help": (
                "Minimum lip-open ratio required to activate the auto-mouth feature. "
                "The ratio is vertical_gap / horizontal_span of the mouth. "
                "Typical conversational values are 0.20–0.50; "
                "above 0.60 only fires for a very wide-open mouth. "
                "Lower values are more sensitive; higher values require a larger opening."
            ),
        },
        "AutoMouthEMAAlphaDecimalSlider": {
            "level": 2,
            "label": "EMA Smoothing",
            "min_value": "0.05",
            "max_value": "1.00",
            "default": "0.40",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "enable_refresh_frame": False,
            "help": (
                "Exponential moving-average factor applied to the detection confidence. "
                "Lower values smooth more aggressively (slower reaction); "
                "1.0 means no smoothing (instant response)."
            ),
        },
        "AutoMouthExpressionStrengthDecimalSlider": {
            "level": 2,
            "label": "Expression Strength",
            "min_value": "0.10",
            "max_value": "1.50",
            "default": "1.00",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "enable_refresh_frame": False,
            "help": (
                "Base expression factor applied to lips when auto-mouth is active. "
                "Actual strength is scaled proportionally with how far above the "
                "threshold the detected confidence is (smooth ramp-in)."
            ),
        },
        "AutoMouthAnimationRegionSelection": {
            "level": 2,
            "label": "Animation Region",
            "options": ["lips", "all"],
            "default": "lips",
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "help": (
                "Used when the face expression restorer is not already enabled. "
                "'lips' transfers only mouth motion. 'all' includes eyes too. "
                "When the restorer is active, eye settings are inherited from it automatically."
            ),
        },
        "AutoMouthNormalizeLipsToggle": {
            "level": 2,
            "label": "Normalize Lips",
            "default": True,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "help": (
                "Enables lip-ratio normalisation for better lip shape accuracy. "
                "In Expression Restorer mode uses lip retargeting (Advanced) or "
                "lp_retarget_lip (Simple/fallback)."
            ),
        },
        "AutoMouthExcludeUpperTeethToggle": {
            "level": 2,
            "label": "Exclude Upper Teeth Area",
            "default": False,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "help": (
                "When auto-mouth is active, trims the top part of the inner-mouth "
                "face-parser mask to keep swapped upper teeth visible while preserving "
                "original inner-mouth content like tongue/cavity."
            ),
        },
        "AutoMouthShowDebugOutlineToggle": {
            "level": 2,
            "label": "Show Mouth Region Outline",
            "default": False,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "help": (
                "Draw a green outline around the mouth region on the preview frame "
                "for debugging. Only visible when Auto Mouth Expression is active."
            ),
        },
        "AutoMouthMouthParserSlider": {
            "level": 2,
            "label": "Mouth Parser",
            "min_value": "0",
            "max_value": "30",
            "default": "1",
            "step": 1,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "enable_refresh_frame": False,
            "help": (
                "Dilation amount for the inner-mouth face-parser mask when auto-mouth "
                "is active. Overrides the Mouth slider in the Face Swap tab."
            ),
        },
        "AutoMouthUpperLipParserSlider": {
            "level": 2,
            "label": "Upper Lip Parser",
            "min_value": "0",
            "max_value": "30",
            "default": "3",
            "step": 1,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "enable_refresh_frame": False,
            "help": (
                "Dilation amount for the upper-lip face-parser mask when auto-mouth "
                "is active. Overrides the Upper Lip slider in the Face Swap tab."
            ),
        },
        "AutoMouthLowerLipParserSlider": {
            "level": 2,
            "label": "Lower Lip Parser",
            "min_value": "0",
            "max_value": "30",
            "default": "8",
            "step": 1,
            "parentToggle": "AutoMouthExpressionEnableToggle",
            "requiredToggleValue": True,
            "enable_refresh_frame": False,
            "help": (
                "Dilation amount for the lower-lip face-parser mask when auto-mouth "
                "is active. Overrides the Lower Lip slider in the Face Swap tab."
            ),
        },
    },
}
