from typing import Any
import app.ui.widgets.actions.control_actions as control_actions

COMMON_LAYOUT_DATA: Any = {
    "面部修复器": {
        "FaceRestorerEnableToggle": {
            "level": 1,
            "label": "启用面部修复器",
            "default": False,
            "help": "启用面部修复模型以提高换脸后的面部质量。",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnableToggle"],
        },
        "FaceRestorerTypeSelection": {
            "level": 2,
            "label": "修复器类型",
            "options": [
                "GFPGAN-v1.4",
                "GFPGAN-1024",
                "CodeFormer",
                "GPEN-256",
                "GPEN-512",
                "GPEN-1024",
                "GPEN-2048",
                "RestoreFormer++",
                "VQFR-v2",
            ],
            "default": "GFPGAN-v1.4",
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "选择面部修复的模型类型。",
            "exec_function": control_actions.handle_model_selection_change,
            "exec_function_args": ["FaceRestorerTypeSelection"],
        },
        "FaceRestorerDetTypeSelection": {
            "level": 2,
            "label": "对齐方式",
            "options": ["Original", "Blend", "Reference"],
            "default": "Original",
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "选择将面部恢复到原始或混合位置的对齐方法。",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnable2Toggle"],
        },
        "FaceFidelityWeightDecimalSlider": {
            "level": 2,
            "label": "保真度权重",
            "min_value": "0.0",
            "max_value": "1.0",
            "default": "0.9",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "调整保真度权重以控制修复过程中保留原始面部细节的程度（仅适用于CodeFormer和VQFR-v2）。",
        },
        "FaceRestorerBlendSlider": {
            "level": 2,
            "label": "混合度",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "控制修复后的面部与换脸后面部之间的混合比例。",
        },
        "FaceRestorerAutoEnableToggle": {
            "level": 2,
            "label": "自动修复",
            "default": False,
            "parentToggle": "FaceRestorerEnableToggle",
            "requiredToggleValue": True,
            "help": "自动调整修复器混合量",
        },
        "FaceRestorerAutoSharpAdjustSlider": {
            "level": 3,
            "label": "调整锐度",
            "min_value": "-60",
            "max_value": "60",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle",
            "requiredToggleValue": True,
            "help": "调整锐度计算。通常需要大于0的值，这会使换脸效果更锐利。取决于换脸模型、修复模型、分辨率、面部大小等因素...",
        },
        "FaceRestorerAutoMaskEnableToggle": {
            "level": 3,
            "label": "锐度掩码",
            "default": False,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle",
            "requiredToggleValue": True,
            "help": "使用锐度图自动调整修复器混合量",
        },
        "FaceRestorerAutoSharpMaskAdjustDecimalSlider": {
            "level": 4,
            "label": "掩码调整",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "FaceRestorerEnableToggle & FaceRestorerAutoEnableToggle & FaceRestorerAutoMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "调整基于自动混合值的最小/最大混合值变化",
        },
        "FaceRestorerEnable2Toggle": {
            "level": 1,
            "label": "启用面部修复器 2",
            "default": False,
            "help": "启用面部修复模型以提高换脸后的面部质量。",
            "exec_function": control_actions.handle_restorer_state_change,
            "exec_function_args": ["FaceRestorerEnable2Toggle"],
        },
        "FaceRestorerEnable2EndToggle": {
            "level": 2,
            "label": "在末尾应用",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "在 pipeline 末尾应用第二个修复器（在面部编辑器之后，以补偿锐度损失，在最终模糊和 jpeg/mpeg 压缩之前。禁用时，直接在第一个修复器之后应用，如原始方式。",
        },
        "FaceRestorerType2Selection": {
            "level": 2,
            "label": "修复器类型",
            "options": [
                "GFPGAN-v1.4",
                "GFPGAN-1024",
                "CodeFormer",
                "GPEN-256",
                "GPEN-512",
                "GPEN-1024",
                "GPEN-2048",
                "RestoreFormer++",
                "VQFR-v2",
            ],
            "default": "GFPGAN-v1.4",
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "选择面部修复的模型类型。",
            "exec_function": control_actions.handle_model_selection_change,
            "exec_function_args": ["FaceRestorerType2Selection"],
        },
        "FaceRestorerDetType2Selection": {
            "level": 2,
            "label": "对齐方式",
            "options": ["Original", "Blend", "Reference"],
            "default": "Original",
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "选择将面部恢复到原始或混合位置的对齐方法。",
        },
        "FaceFidelityWeight2DecimalSlider": {
            "level": 2,
            "label": "保真度权重",
            "min_value": "0.0",
            "max_value": "1.0",
            "default": "0.9",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "调整保真度权重以控制修复过程中保留原始面部细节的程度。",
        },
        "FaceRestorerBlend2Slider": {
            "level": 2,
            "label": "混合度",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "控制修复后的面部与换脸后面部之间的混合比例。",
        },
        "FaceRestorerAutoEnable2Toggle": {
            "level": 2,
            "label": "自动修复2",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle",
            "requiredToggleValue": True,
            "help": "自动调整修复器2混合量",
        },
        "FaceRestorerAutoSharpAdjust2Slider": {
            "level": 3,
            "label": "调整锐度",
            "min_value": "-60",
            "max_value": "60",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle",
            "requiredToggleValue": True,
            "help": "调整锐度计算。通常需要大于0的值，这会使换脸效果更锐利。取决于换脸模型、修复模型、分辨率、面部大小等因素...",
        },
        "FaceRestorerAutoMask2EnableToggle": {
            "level": 3,
            "label": "锐度掩码",
            "default": False,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle",
            "requiredToggleValue": True,
            "help": "使用锐度图自动调整修复器混合量",
        },
        "FaceRestorerAutoSharpMask2AdjustDecimalSlider": {
            "level": 4,
            "label": "掩码调整",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "FaceRestorerEnable2Toggle & FaceRestorerAutoEnable2Toggle & FaceRestorerAutoMask2EnableToggle",
            "requiredToggleValue": True,
            "help": "调整基于自动混合值的最小/最大混合值变化",
        },
    },
    "面部表情": {
        "FaceExpressionBeforeTypeSelection": {
            "level": 1,
            "label": "Pipeline 位置",
            "options": ["Beginning", "After First Restorer", "After Second Restorer"],
            "default": "Beginning",
            "help": "选择面部表情修复编辑器在 pipeline 中的位置。",
        },
        "FaceExpressionEnableBothToggle": {
            "level": 1,
            "label": "启用面部表情修复器",
            "default": False,
            "help": "启用 LivePortrait 面部表情模型，用于在换脸后恢复面部表情。",
            "exec_function": control_actions.handle_face_expression_toggle_change,
            "exec_function_args": ["FaceExpressionEnableBothToggle"],
        },
        "FaceExpressionModeSelection": {
            "level": 2,
            "label": "模式",
            "options": ["Simple", "Advanced"],
            "default": "Simple",
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "选择 'Advanced' 以获得微调和重新定位选项。",
        },
        "FaceExpressionCropScaleBothDecimalSlider": {
            "level": 2,
            "label": "裁剪比例",
            "min_value": "1.7",
            "max_value": "3.0",
            "default": "2.3",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "更改换脸裁剪比例。增加值以更远距离地捕捉面部。",
        },
        "FaceExpressionVYRatioBothDecimalSlider": {
            "level": 2,
            "label": "VY 比例",
            "min_value": "-0.125",
            "max_value": "-0.100",
            "default": "-0.125",
            "step": 0.001,
            "decimals": 3,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "更改裁剪比例的 vy 比例。增加值以更远距离地捕捉面部。",
        },
        "FaceExpressionNeutralDecimalSlider": {
            "level": 2,
            "label": "中性因子",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "0.30",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "help": "要添加的表情百分比。换脸后的面部已经因换脸而具有一些表情，不建议添加完整表情，滑块值应低于1.0。",
        },
        # --- SIMPLE MODE WIDGETS (RESTORING OLD FUNCTIONALITY) ---
        "FaceExpressionFriendlyFactorDecimalSlider": {
            "level": 3,
            "label": "表情因子",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Simple",
            "help": "控制驱动面部与换脸后面部之间的表情相似度。",
        },
        "FaceExpressionAnimationRegionSelection": {
            "level": 3,
            "label": "动画区域",
            "options": ["all", "eyes", "lips"],
            "default": "all",
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Simple",
            "help": "参与修复过程的面部区域。",
        },
        "FaceExpressionNormalizeLipsEnableToggle": {
            "level": 3,
            "label": "标准化嘴唇",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Simple",
            "help": "在面部修复过程中标准化嘴唇。",
        },
        "FaceExpressionNormalizeLipsThresholdDecimalSlider": {
            "level": 4,
            "label": "标准化嘴唇阈值",
            "min_value": "0.10",
            "max_value": "1.00",
            "default": "0.03",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeLipsEnableToggle & FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Simple",
            "help": "标准化嘴唇的阈值。",
        },
        # --- ADVANCED MODE WIDGETS (CURRENT LAYOUT) ---
        "FaceExpressionMicroExpressionBoostDecimalSlider": {
            "level": 3,
            "label": "微表情增强",
            "min_value": "0.80",
            "max_value": "1.50",
            "default": "1.00",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "使用相对运动时放大动作。默认值为 1.00。",
        },
        "FaceExpressionEyesToggle": {
            "level": 3,
            "label": "恢复眼睛",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "激活眼睛面部表情恢复器",
        },
        "FaceExpressionRelativeEyesToggle": {
            "level": 4,
            "label": "相对位置",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "使动画相对于源图像的初始姿势。可以获得更自然的外观。",
        },
        "FaceExpressionFriendlyFactorEyesDecimalSlider": {
            "level": 4,
            "label": "眼睛表情因子",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "控制驱动面部与换脸后面部之间的眼睛表情相似度。",
        },
        "FaceExpressionRetargetingEyesBothEnableToggle": {
            "level": 4,
            "label": "眼睛重定向",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "在面部恢复过程中调整或重定向眼睛的凝视或运动。",
        },
        "FaceExpressionRetargetingEyesMultiplierBothDecimalSlider": {
            "level": 5,
            "label": "眼睛乘数",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionRetargetingEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "眼睛重定向的乘数。",
        },
        "FaceExpressionNormalizeEyesBothEnableToggle": {
            "level": 5,
            "label": "标准化眼睛",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "在面部恢复过程中标准化眼睛。",
        },
        "FaceExpressionNormalizeEyesThresholdBothDecimalSlider": {
            "level": 6,
            "label": "眼睛阈值",
            "min_value": "0.10",
            "max_value": "1.00",
            "default": "0.40",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "眼睛睁开比例的阈值，它将决定在哪个睁开/闭合比例下使用修改后的 faceutil 函数。",
        },
        "FaceExpressionNormalizeEyesMaxBothDecimalSlider": {
            "level": 6,
            "label": "最大睁开比例",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "0.45",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeEyesBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionEyesToggle & FaceExpressionRetargetingEyesBothEnableToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "目标将拥有的最大眼睛睁开比例（<0.5 最佳）。",
        },
        "FaceExpressionBrowsToggle": {
            "level": 3,
            "label": "恢复眉毛",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "激活眉毛的恢复。",
        },
        "FaceExpressionRelativeBrowsToggle": {
            "level": 4,
            "label": "相对位置",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionBrowsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "使动画相对于源图像的初始姿势。减少面部形状的几何扭曲。",
        },
        "FaceExpressionFriendlyFactorBrowsDecimalSlider": {
            "level": 4,
            "label": "眉毛表情因子",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionBrowsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "控制眉毛的表情强度。",
        },
        "FaceExpressionLipsToggle": {
            "level": 3,
            "label": "恢复嘴唇",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "激活嘴唇面部表情恢复器",
        },
        "FaceExpressionRelativeLipsToggle": {
            "level": 4,
            "label": "相对位置",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "使动画相对于源图像的初始姿势。可以获得更自然的外观。",
        },
        "FaceExpressionFriendlyFactorLipsDecimalSlider": {
            "level": 4,
            "label": "嘴唇表情因子",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "控制驱动面部与换脸后面部之间的嘴唇表情相似度。",
        },
        "FaceExpressionRetargetingLipsBothEnableToggle": {
            "level": 4,
            "label": "嘴唇重定向",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "在面部恢复过程中调整或修改嘴唇的位置、形状或运动。",
        },
        "FaceExpressionRetargetingLipsMultiplierBothDecimalSlider": {
            "level": 5,
            "label": "嘴唇乘数",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionRetargetingLipsBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "嘴唇重定向的乘数。",
        },
        "FaceExpressionNormalizeLipsBothEnableToggle": {
            "level": 4,
            "label": "标准化嘴唇",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "在面部恢复过程中标准化嘴唇。",
        },
        "FaceExpressionNormalizeLipsThresholdBothDecimalSlider": {
            "level": 5,
            "label": "嘴唇阈值",
            "min_value": "0.00",
            "max_value": "0.20",
            "default": "0.03",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceExpressionNormalizeLipsBothEnableToggle & FaceExpressionEnableBothToggle & FaceExpressionLipsToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "标准化嘴唇的阈值。",
        },
        "FaceExpressionGeneralToggle": {
            "level": 3,
            "label": "恢复一般面部特征",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "激活一般表情的恢复。（在 frame_edits.py 中注释或取消注释面部部分以获得更多控制）",
        },
        "FaceExpressionRelativeGeneralToggle": {
            "level": 4,
            "label": "相对位置",
            "default": False,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "使动画相对于源图像的初始姿势。减少面部形状的几何扭曲。",
        },
        "FaceExpressionGeneralNoseToggle": {
            "level": 4,
            "label": "包含鼻子",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "将鼻子索引添加到一般表情中。",
        },
        "FaceExpressionGeneralJawToggle": {
            "level": 4,
            "label": "包含下巴",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "将下巴索引添加到一般表情中。",
        },
        "FaceExpressionGeneralCheekToggle": {
            "level": 4,
            "label": "包含脸颊",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "将脸颊索引添加到一般表情中。",
        },
        "FaceExpressionGeneralContourToggle": {
            "level": 4,
            "label": "包含轮廓",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "将轮廓索引添加到一般表情中。",
        },
        "FaceExpressionGeneralHeadToggle": {
            "level": 4,
            "label": "包含头顶",
            "default": True,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "将头顶索引添加到一般表情中。",
        },
        "FaceExpressionFriendlyFactorGeneralDecimalSlider": {
            "level": 4,
            "label": "一般表情因子",
            "min_value": "0.0",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "FaceExpressionEnableBothToggle & FaceExpressionGeneralToggle",
            "requiredToggleValue": True,
            "parentSelection": "FaceExpressionModeSelection",
            "requiredSelectionValue": "Advanced",
            "help": "控制一般特征的表情强度。",
        },
    },
}
