from typing import Any
import app.ui.widgets.actions.control_actions as control_actions

DENOISER_LAYOUT_DATA: Any = {
    "ReF-LDM 降噪器": {
        "UseReferenceExclusivePathToggle": {  # New ToggleButton
            "level": 1,
            "widget_type": "ToggleButton",
            "label": "独占参考路径",
            "control_name": "UseReferenceExclusivePathToggle",
            "default": True,
            "help": "如果启用，强制 UNet 仅使用参考 K/V 进行注意力计算，最大化对参考特征的关注。",
            "exec_function": control_actions.handle_denoiser_state_change,
            "exec_function_args": ["UseReferenceExclusivePathToggle"],
        },
        "DenoiserBaseSeedSlider": {
            "level": 1,
            "widget_type": "ParameterSlider",
            "label": "基础种子",
            "control_name": "DenoiserBaseSeedSlider",
            "min_value": "1",
            "max_value": "999",
            "default": "220",
            "step": 1,
            "help": "为降噪器设置固定的基础种子。此种子将用于所有帧和两次降噪器通道（如果适用），以确保一致的噪声模式。",
        },
        "DenoiserUNetEnableBeforeRestorersToggle": {
            "level": 1,
            "widget_type": "ToggleButton",
            "label": "在修复器之前启用降噪器",
            "control_name": "DenoiserUNetEnableBeforeRestorersToggle",
            "default": False,
            "help": "启用基于 UNet 的图像降噪。这会应用于 512x512 对齐/换脸后的面部，在其他修复器之前。",
            "exec_function": control_actions.handle_denoiser_state_change,
            "exec_function_args": ["DenoiserUNetEnableBeforeRestorersToggle"],
        },
        "DenoiserModeSelectionBefore": {
            "level": 2,
            "widget_type": "SelectionBox",
            "label": "降噪模式（之前）",
            "control_name": "DenoiserModeSelectionBefore",
            "options": ["Single Step (Fast)", "Full Restore (DDIM)"],
            "default": "Single Step (Fast)",
            "parentToggle": "DenoiserUNetEnableBeforeRestorersToggle",
            "requiredToggleValue": True,
            "help": "修复器之前通道的降噪模式。单步通常更快。",
        },
        "DenoiserSingleStepTimestepSliderBefore": {
            "level": 3,
            "widget_type": "ParameterSlider",
            "label": "单步时间步长 (t)（之前）",
            "control_name": "DenoiserSingleStepTimestepSliderBefore",
            "min_value": "1",
            "max_value": "500",
            "default": "1",
            "step": 1,
            "parentToggle": "DenoiserUNetEnableBeforeRestorersToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionBefore",
            "requiredSelectionValue": "Single Step (Fast)",
            "help": "单步降噪的时间步长（修复器之前）。值越低，添加/移除的噪声越少。",
        },
        "DenoiserDDIMStepsSliderBefore": {
            "level": 3,
            "widget_type": "ParameterSlider",
            "label": "DDIM 步数（之前）",
            "control_name": "DenoiserDDIMStepsSliderBefore",
            "min_value": "1",
            "max_value": "300",
            "default": "10",
            "step": 1,
            "parentToggle": "DenoiserUNetEnableBeforeRestorersToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionBefore",
            "requiredSelectionValue": "Full Restore (DDIM)",
            "help": "完全恢复的 DDIM 步数（修复器之前）。值越高，细节越多，但速度越慢。",
        },
        "DenoiserCFGScaleDecimalSliderBefore": {
            "level": 3,
            "widget_type": "ParameterDecimalSlider",
            "label": "CFG 缩放（之前）",
            "control_name": "DenoiserCFGScaleDecimalSliderBefore",
            "min_value": "0.0",
            "max_value": "10.0",
            "default": "1.0",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "DenoiserUNetEnableBeforeRestorersToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionBefore",
            "requiredSelectionValue": "Full Restore (DDIM)",
            "help": "DDIM 的无分类器引导缩放（修复器之前）。值越高，对 K/V 的 adherence 越强。",
        },
        "DenoiserLatentSharpeningDecimalSliderBefore": {
            "level": 3,
            "widget_type": "ParameterDecimalSlider",
            "label": "潜在空间锐化（之前）",
            "control_name": "DenoiserLatentSharpeningSliderBefore",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "0.0",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "DenoiserUNetEnableBeforeRestorersToggle",
            "requiredToggleValue": True,
            "help": "在解码前直接在潜在空间中增强细节。",
        },
        # --- AFTER FIRST RESTORER ---
        "DenoiserAfterFirstRestorerToggle": {
            "level": 1,
            "widget_type": "ToggleButton",
            "label": "在第一个修复器后启用降噪器",
            "control_name": "DenoiserAfterFirstRestorerToggle",
            "default": False,
            "help": "在应用第一个修复器后再次应用 UNet 降噪器。使用相同的 UNet 模型和步骤设置。",
            "exec_function": control_actions.handle_denoiser_state_change,
            "exec_function_args": ["DenoiserAfterFirstRestorerToggle"],
        },
        "DenoiserModeSelectionAfterFirst": {
            "level": 2,
            "widget_type": "SelectionBox",
            "label": "降噪模式（第一个之后）",
            "control_name": "DenoiserModeSelectionAfterFirst",
            "options": ["Single Step (Fast)", "Full Restore (DDIM)"],
            "default": "Single Step (Fast)",
            "parentToggle": "DenoiserUNetEnableAfterFirstRestorerToggle",
            "requiredToggleValue": True,
            "help": "第一个修复器后通道的降噪模式。单步通常更快。",
        },
        "DenoiserSingleStepTimestepSliderAfterFirst": {
            "level": 3,
            "widget_type": "ParameterSlider",
            "label": "单步时间步长 (t)（第一个之后）",
            "control_name": "DenoiserSingleStepTimestepSliderAfterFirst",
            "min_value": "1",
            "max_value": "500",
            "default": "1",
            "step": 1,
            "parentToggle": "DenoiserUNetEnableAfterFirstRestorerToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionAfterFirst",
            "requiredSelectionValue": "Single Step (Fast)",
            "help": "单步降噪的时间步长（第一个修复器之后）。值越低，添加/移除的噪声越少。",
        },
        "DenoiserDDIMStepsSliderAfterFirst": {
            "level": 3,
            "widget_type": "ParameterSlider",
            "label": "DDIM 步数（第一个之后）",
            "control_name": "DenoiserDDIMStepsSliderAfterFirst",
            "min_value": "1",
            "max_value": "300",
            "default": "10",
            "step": 1,
            "parentToggle": "DenoiserUNetEnableAfterFirstRestorerToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionAfterFirst",
            "requiredSelectionValue": "Full Restore (DDIM)",
            "help": "完全恢复的 DDIM 步数（第一个修复器之后）。值越高，细节越多，但速度越慢。",
        },
        "DenoiserCFGScaleDecimalSliderAfterFirst": {
            "level": 3,
            "widget_type": "ParameterDecimalSlider",
            "label": "CFG 缩放（第一个之后）",
            "control_name": "DenoiserCFGScaleDecimalSliderAfterFirst",
            "min_value": "0.0",
            "max_value": "10.0",
            "default": "1.0",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "DenoiserUNetEnableAfterFirstRestorerToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionAfterFirst",
            "requiredSelectionValue": "Full Restore (DDIM)",
            "help": "DDIM 的无分类器引导缩放（第一个修复器之后）。值越高，对 K/V 的 adherence 越强。",
        },
        "DenoiserLatentSharpeningDecimalSliderAfterFirst": {
            "level": 3,
            "widget_type": "ParameterDecimalSlider",
            "label": "潜在空间锐化（第一个之后）",
            "control_name": "DenoiserLatentSharpeningSliderAfterFirst",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "0.0",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "DenoiserAfterFirstRestorerToggle",
            "requiredToggleValue": True,
            "help": "在解码前直接在潜在空间中增强细节。",
        },
        # --- AFTER RESTORERS (END) ---
        "DenoiserAfterRestorersToggle": {
            "level": 1,
            "widget_type": "ToggleButton",
            "label": "在修复器后启用降噪器",
            "control_name": "DenoiserAfterRestorersToggle",
            "default": False,
            "help": "在应用面部修复器后再次应用 UNet 降噪器。使用相同的 UNet 模型和步骤设置。",
            "exec_function": control_actions.handle_denoiser_state_change,
            "exec_function_args": ["DenoiserAfterRestorersToggle"],
        },
        "DenoiserModeSelectionAfter": {
            "level": 2,
            "widget_type": "SelectionBox",
            "label": "降噪模式（之后）",
            "control_name": "DenoiserModeSelectionAfter",
            "options": ["Single Step (Fast)", "Full Restore (DDIM)"],
            "default": "Single Step (Fast)",
            "parentToggle": "DenoiserAfterRestorerToggle",
            "requiredToggleValue": True,
            "help": "修复器后通道的降噪模式。单步通常更快。",
        },
        "DenoiserSingleStepTimestepSliderAfter": {
            "level": 3,
            "widget_type": "ParameterSlider",
            "label": "单步时间步长 (t)（之后）",
            "control_name": "DenoiserSingleStepTimestepSliderAfter",
            "min_value": "1",
            "max_value": "500",
            "default": "1",
            "step": 1,
            "parentToggle": "DenoiserAfterRestorerToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionAfter",
            "requiredSelectionValue": "Single Step (Fast)",
            "help": "单步降噪的时间步长（修复器之后）。值越低，添加/移除的噪声越少。",
        },
        "DenoiserDDIMStepsSliderAfter": {
            "level": 3,
            "widget_type": "ParameterSlider",
            "label": "DDIM 步数（之后）",
            "control_name": "DenoiserDDIMStepsSliderAfter",
            "min_value": "1",
            "max_value": "300",
            "default": "10",
            "step": 1,
            "parentToggle": "DenoiserAfterRestorerToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionAfter",
            "requiredSelectionValue": "Full Restore (DDIM)",
            "help": "完全恢复的 DDIM 步数（修复器之后）。值越高，细节越多，但速度越慢。",
        },
        "DenoiserCFGScaleDecimalSliderAfter": {
            "level": 3,
            "widget_type": "ParameterDecimalSlider",
            "label": "CFG 缩放（之后）",
            "control_name": "DenoiserCFGScaleDecimalSliderAfter",
            "min_value": "0.0",
            "max_value": "10.0",
            "default": "1.0",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "DenoiserAfterRestorerToggle",
            "requiredToggleValue": True,
            "parentSelection": "DenoiserModeSelectionAfter",
            "requiredSelectionValue": "Full Restore (DDIM)",
            "help": "DDIM 的无分类器引导缩放（修复器之后）。值越高，对 K/V 的 adherence 越强。",
        },
        "DenoiserLatentSharpeningDecimalSliderAfter": {
            "level": 3,
            "widget_type": "ParameterDecimalSlider",
            "label": "潜在空间锐化（之后）",
            "control_name": "DenoiserLatentSharpeningSliderAfter",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "0.0",
            "step": 0.1,
            "decimals": 1,
            "parentToggle": "DenoiserAfterRestorersToggle",
            "requiredToggleValue": True,
            "help": "在解码前直接在潜在空间中增强细节。推荐值：0.15。",
        },
    }
}
