from typing import Any

FACE_EDITOR_LAYOUT_DATA: Any = {  # noqa: F811
    "": {
        "FaceEditorBeforeTypeSelection": {
            "level": 1,
            "label": "处理流程位置",
            "options": [
                "开始",
                "第一个修复器之后",
                "纹理转移之后",
                "第二个修复器之后",
            ],
            "default": "开始",
            "help": "选择面部姿势/表情编辑器在处理流程中的位置。",
        },
        "FaceEditorCropScaleDecimalSlider": {
            "level": 1,
            "label": "裁剪比例",
            "min_value": "1.50",
            "max_value": "4.00",
            "default": "2.50",
            "step": 0.05,
            "decimals": 2,
            "help": "更改源裁剪比例。增加值以更远距离地捕捉面部。驱动视频裁剪的比例因子为 2.2。",
        },
        "FaceEditorVYRatioDecimalSlider": {
            "level": 1,
            "label": "VY 比例",
            "min_value": "-0.200",
            "max_value": "0.200",
            "default": "-0.125",
            "step": 0.001,
            "decimals": 3,
            "help": "更改裁剪比例的 vy 比例。增加值以更远距离地捕捉面部。驱动视频裁剪的因子为 -0.1。",
        },
        "FaceEditorBlurAmountSlider": {
            "level": 1,
            "label": "模糊量",
            "min_value": "0",
            "max_value": "100",
            "default": "5",
            "step": 1,
            "help": "模糊量。",
        },
        "FaceEditorEnableToggle": {
            "level": 1,
            "label": "启用面部姿势/表情编辑器",
            "default": False,
            "help": "启用面部姿势/表情编辑器。",
        },
        "FaceEditorTypeSelection": {
            "level": 2,
            "label": "面部编辑器类型",
            #'options': ['Human-Face', 'Animal-Face'],
            "options": ["Human-Face"],
            "default": "Human-Face",
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "选择要在面部编辑器中编辑的目标类型。",
        },
        "EyesOpenRatioDecimalSlider": {
            "level": 2,
            "label": "眼睛闭合 <--> 睁开比例",
            "min_value": "-0.80",
            "max_value": "0.80",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改眼睛的睁开程度。",
        },
        "LipsOpenRatioDecimalSlider": {
            "level": 2,
            "label": "嘴唇闭合 <--> 张开比例",
            "min_value": "-0.80",
            "max_value": "0.80",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改嘴唇的张开程度。",
        },
        "HeadPitchSlider": {
            "level": 2,
            "label": "头部俯仰",
            "min_value": "-15",
            "max_value": "15",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改头部的俯仰角度。",
        },
        "HeadYawSlider": {
            "level": 2,
            "label": "头部偏航",
            "min_value": "-15",
            "max_value": "15",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改头部的偏航角度。",
        },
        "HeadRollSlider": {
            "level": 2,
            "label": "头部翻滚",
            "min_value": "-15",
            "max_value": "15",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改头部的翻滚角度。",
        },
        "XAxisMovementDecimalSlider": {
            "level": 2,
            "label": "X轴移动",
            "min_value": "-0.19",
            "max_value": "0.19",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改头部在 X 轴上的方向。",
        },
        "YAxisMovementDecimalSlider": {
            "level": 2,
            "label": "Y轴移动",
            "min_value": "-0.19",
            "max_value": "0.19",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改头部在 Y 轴上的方向。",
        },
        "ZAxisMovementDecimalSlider": {
            "level": 2,
            "label": "Z轴移动",
            "min_value": "-0.90",
            "max_value": "1.20",
            "default": "1.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改头部在 Z 轴上的方向。",
        },
        "MouthPoutingDecimalSlider": {
            "level": 2,
            "label": "嘴巴撅起",
            "min_value": "-0.09",
            "max_value": "0.09",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "撅起嘴巴。",
        },
        "MouthPursingDecimalSlider": {
            "level": 2,
            "label": "嘴巴噘起",
            "min_value": "-20.00",
            "max_value": "15.00",
            "default": "0.00",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "噘起嘴巴。",
        },
        "MouthGrinDecimalSlider": {
            "level": 2,
            "label": "嘴巴露齿笑",
            "min_value": "0.00",
            "max_value": "15.00",
            "default": "0.00",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改嘴巴的露齿笑程度。",
        },
        "LipsCloseOpenSlider": {
            "level": 2,
            "label": "嘴唇闭合 <--> 张开值",
            "min_value": "-90",
            "max_value": "120",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改嘴唇的闭合或张开程度。",
        },
        "MouthSmileDecimalSlider": {
            "level": 2,
            "label": "嘴巴微笑",
            "min_value": "-0.80",
            "max_value": "1.30",
            "default": "0.00",
            "step": 0.05,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改嘴巴的微笑程度。",
        },
        "EyeWinkDecimalSlider": {
            "level": 2,
            "label": "眼睛眨眼",
            "min_value": "0.00",
            "max_value": "39.00",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "眨眼效果。",
        },
        "EyeBrowsDirectionDecimalSlider": {
            "level": 2,
            "label": "眉毛方向",
            "min_value": "-30.00",
            "max_value": "30.00",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改眉毛的方向。",
        },
        "EyeGazeHorizontalDecimalSlider": {
            "level": 2,
            "label": "眼睛水平注视",
            "min_value": "-30.00",
            "max_value": "30.00",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改眼睛水平注视方向。",
        },
        "EyeGazeVerticalDecimalSlider": {
            "level": 2,
            "label": "眼睛垂直注视",
            "min_value": "-63.00",
            "max_value": "63.00",
            "default": "0.00",
            "step": 0.01,
            "decimals": 2,
            "parentToggle": "FaceEditorEnableToggle",
            "requiredToggleValue": True,
            "help": "更改眼睛垂直注视方向。",
        },
        "FaceMakeupEnableToggle": {
            "level": 1,
            "label": "面部妆容",
            "default": False,
            "help": "启用面部妆容。不包括头发、眉毛、眼睛和嘴唇。",
        },
        "FaceMakeupRedSlider": {
            "level": 2,
            "label": "红色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "红色调整。",
        },
        "FaceMakeupGreenSlider": {
            "level": 2,
            "label": "绿色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 3,
            "parentToggle": "FaceMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "绿色调整。",
        },
        "FaceMakeupBlueSlider": {
            "level": 2,
            "label": "蓝色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "蓝色调整。",
        },
        "FaceMakeupBlendAmountDecimalSlider": {
            "level": 2,
            "label": "混合量",
            "min_value": "0.01",
            "max_value": "1.00",
            "default": "0.05",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "FaceMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "混合值：0.00 表示原始颜色，1.00 表示完整目标颜色。",
        },
        "HairMakeupEnableToggle": {
            "level": 1,
            "label": "头发妆容",
            "default": False,
            "help": "启用头发妆容。",
        },
        "HairMakeupRedSlider": {
            "level": 2,
            "label": "红色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 1,
            "parentToggle": "HairMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "红色调整。",
        },
        "HairMakeupGreenSlider": {
            "level": 2,
            "label": "绿色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 3,
            "parentToggle": "HairMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "绿色调整。",
        },
        "HairMakeupBlueSlider": {
            "level": 2,
            "label": "蓝色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 1,
            "parentToggle": "HairMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "蓝色调整。",
        },
        "HairMakeupBlendAmountDecimalSlider": {
            "level": 2,
            "label": "混合量",
            "min_value": "0.01",
            "max_value": "1.00",
            "default": "0.05",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "HairMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "混合值：0.00 表示原始颜色，1.00 表示完整目标颜色。",
        },
        "EyeBrowsMakeupEnableToggle": {
            "level": 1,
            "label": "眉毛妆容",
            "default": False,
            "help": "启用眉毛妆容。",
        },
        "EyeBrowsMakeupRedSlider": {
            "level": 2,
            "label": "红色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 1,
            "parentToggle": "EyeBrowsMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "红色调整。",
        },
        "EyeBrowsMakeupGreenSlider": {
            "level": 2,
            "label": "绿色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 3,
            "parentToggle": "EyeBrowsMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "绿色调整。",
        },
        "EyeBrowsMakeupBlueSlider": {
            "level": 2,
            "label": "蓝色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 1,
            "parentToggle": "EyeBrowsMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "蓝色调整。",
        },
        "EyeBrowsMakeupBlendAmountDecimalSlider": {
            "level": 2,
            "label": "混合量",
            "min_value": "0.01",
            "max_value": "1.00",
            "default": "0.05",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "EyeBrowsMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "混合值：0.00 表示原始颜色，1.00 表示完整目标颜色。",
        },
        "LipsMakeupEnableToggle": {
            "level": 1,
            "label": "嘴唇妆容",
            "default": False,
            "help": "启用嘴唇妆容。",
        },
        "LipsMakeupRedSlider": {
            "level": 2,
            "label": "红色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 1,
            "parentToggle": "LipsMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "红色调整。",
        },
        "LipsMakeupGreenSlider": {
            "level": 2,
            "label": "绿色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 3,
            "parentToggle": "LipsMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "绿色调整。",
        },
        "LipsMakeupBlueSlider": {
            "level": 2,
            "label": "蓝色",
            "min_value": "0",
            "max_value": "255",
            "default": "0",
            "step": 1,
            "parentToggle": "LipsMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "蓝色调整。",
        },
        "LipsMakeupBlendAmountDecimalSlider": {
            "level": 2,
            "label": "混合量",
            "min_value": "0.01",
            "max_value": "1.00",
            "default": "0.05",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "LipsMakeupEnableToggle",
            "requiredToggleValue": True,
            "help": "混合值：0.0 表示原始颜色，1.0 表示完整目标颜色。",
        },
    }
}
