from app.ui.widgets.actions import control_actions
import cv2
from typing import Any

SETTINGS_LAYOUT_DATA: Any = {  # noqa: F811
    "外观": {
        "ThemeSelection": {
            "level": 1,
            "label": "主题",
            "options": [
                "True-Dark",
                "Dark",
                "Dark-Blue",
                "Light",
                "Solarized-Dark",
                "Solarized-Light",
                "Dracula",
                "Nord",
                "Gruvbox",
            ],
            "default": "True-Dark",
            "help": "选择要使用的主题",
            "exec_function": control_actions.change_theme,
            "exec_function_args": [],
        }
    },
    "通用": {
        "ProvidersPrioritySelection": {
            "level": 1,
            "label": "提供者优先级",
            "options": ["CUDA", "TensorRT", "TensorRT-Engine", "CPU"],
            "default": "TensorRT",
            "help": "选择系统使用的提供者优先级。",
            "exec_function": control_actions.change_execution_provider,
            "exec_function_args": [],
        },
        "nThreadsSlider": {
            "level": 1,
            "label": "线程数量",
            "min_value": "1",
            "max_value": "30",
            "default": "4",
            "step": 1,
            "help": "设置播放和录制时的执行线程数。强烈依赖于 GPU 显存。",
            "exec_function": control_actions.change_threads_number,
            "exec_function_args": [],
        },
        "KeepControlsToggle": {
            "level": 1,
            "label": "保持控件激活",
            "default": False,
            "help": "在录制过程中保持控件激活。",
        },
        "TrackMarkersToggle": {
            "level": 1,
            "label": "视频 seek 时跟踪标记",
            "default": False,
            "help": "当 seek 视频时更新参数和控件，以反映其位置的选项状态。",
        },
        "GlobalInputResizeToggle": {
            "level": 1,
            "label": "调整输入源大小（性能/输出）",
            "default": False,
            "help": "在处理前缩小输入视频/图像。提高性能并将最终输出分辨率设置为所选大小。",
        },
        "GlobalInputResizeSizeSelection": {
            "level": 2,
            "label": "输入分辨率目标",
            "options": ["540p", "720p", "1080p"],
            "default": "720p",
            "parentToggle": "GlobalInputResizeToggle",
            "requiredToggleValue": True,
            "help": "目标高度分辨率（例如 720p）。保持宽高比。",
        },
    },
    "视频播放设置": {
        "VideoPlaybackCustomFpsToggle": {
            "level": 1,
            "label": "设置自定义视频播放 FPS",
            "default": False,
            "help": "手动设置播放视频时使用的 FPS",
            "exec_function": control_actions.set_video_playback_fps,
            "exec_function_args": [],
        },
        "VideoPlaybackCustomFpsSlider": {
            "level": 2,
            "label": "视频播放 FPS",
            "min_value": "1",
            "max_value": "120",
            "default": "30",
            "parentToggle": "VideoPlaybackCustomFpsToggle",
            "requiredToggleValue": True,
            "step": 1,
            "help": "设置播放时视频的最大 FPS",
        },
        "VideoPlaybackBufferingToggle": {
            "level": 1,
            "label": "播放缓冲",
            "default": False,
            "help": "激活缓冲以获得更流畅的视频播放。",
        },
        "VideoPlaybackLoopToggle": {
            "level": 1,
            "label": "播放循环",
            "default": False,
            "help": "视频播放到结束时自动重新开始。（对录制无效）",
        },
        "LiveSoundVolumeDecimalSlider": {
            "level": 1,
            "label": "音频播放音量",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "1.00",
            "step": 0.01,
            "decimals": 2,
            "help": "设置音频的播放音量，当启用实时声音时",
        },
        "LiveSoundDelayDecimalSlider": {
            "level": 1,
            "label": "音频开始延迟（秒）",
            "min_value": "0.00",
            "max_value": "3.00",
            "default": "0.30",
            "step": 0.01,
            "decimals": 2,
            "help": "设置音频开始延迟以调整延迟。",
        },
    },
    "视频录制设置": {
        "FrameEnhancerDownToggle": {
            "level": 1,
            "label": "将帧调整为 1920*1080",
            "default": False,
            "help": "选择将视频调整为 1920*1080（仅适用于 16/9 格式）",
        },
        "OpenOutputToggle": {
            "level": 1,
            "label": "录制后打开输出文件夹",
            "default": False,
            "help": "录制结束后打开输出文件夹。",
        },
        "HDREncodeToggle": {
            "level": 1,
            "label": "HDR 编码 - 仅在 HDR 视频上使用 (CPU)",
            "default": False,
            "help": "以 HDR 编码视频文件，使用 CPU 和 libx256，处理速度较慢。",
        },
        "FFMpegOptionsToggle": {
            "level": 1,
            "label": "FFMpeg 选项",
            "default": False,
            "help": "显示 FFMpeg 选项。",
        },
        "FFPresetsSDRSelection": {
            "level": 2,
            "label": "预设 SDR",
            "options": ["p1", "p2", "p3", "p4", "p5", "p6", "p7"],
            "default": "p5",
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "HEVC_NVENC 预设，P1 = 更快但质量更低 → P7 = 更慢但质量更好。默认 = P5。",
        },
        "FFPresetsHDRSelection": {
            "level": 2,
            "label": "预设 HDR",
            "options": [
                "ultrafast",
                "superfast",
                "veryfast",
                "faster",
                "fast",
                "medium",
                "slow",
                "veryslow",
            ],
            "default": "slow",
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "LIBx265 预设，Ultrafast = 更快但质量更低 → Veryslow = 更慢但质量更好。默认 = Slow。",
        },
        "FFQualitySlider": {
            "level": 2,
            "label": "质量",
            "min_value": "0",
            "max_value": "51",
            "default": "18",
            "step": 1,
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "恒定质量滑块，值越低 = 质量越好但编码越少（文件越大）。默认 = 18。",
        },
        "FFSpatialAQToggle": {
            "level": 2,
            "label": "空间 AQ",
            "default": False,
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "空间 AQ 根据内容复杂度调整单个帧内的 QP。它为细节丰富或纹理区域分配更多比特，为平坦、均匀区域分配更少比特。",
        },
        "FFTemporalAQToggle": {
            "level": 2,
            "label": "时间 AQ",
            "default": False,
            "parentToggle": "FFMpegOptionsToggle",
            "requiredToggleValue": True,
            "help": "时间 AQ 随时间调整多个帧的 QP。它通过减轻帧之间的比特率和质量波动来帮助保持一致的视觉质量。",
        },
    },
    "换脸设置": {
        "AutoSwapToggle": {
            "level": 1,
            "label": "自动换脸",
            "default": False,
            "help": "加载视频/图像文件时使用选定的源面部/嵌入自动换脸所有面部",
        },
        "KeepInputToggle": {
            "level": 1,
            "label": "保持选定的输入面部/嵌入",
            "default": False,
            "help": "切换目标媒体时保持选定的输入面部或嵌入。",
        },
        "SwapOnlyBestMatchEnableToggle": {
            "level": 1,
            "label": "仅交换一次输入面部",
            "default": False,
            "help": "每个面部仅交换最高匹配度的面部（不是每个超过阈值的匹配）",
        },
        "VR180ModeEnableToggle": {
            "level": 1,
            "label": "启用 VR180 模式",
            "default": False,
            "help": "启用 VR180 模式。这将把输入视频视为 equirectangular VR180 视频，并在透视裁剪中应用换脸。",
        },
        "MaxDFMModelsSlider": {
            "level": 1,
            "label": "最大使用的 DFM 模型数量",
            "min_value": "1",
            "max_value": "5",
            "default": "1",
            "step": 1,
            "help": "设置一次在内存中保留的最大 DFM 模型数量。根据您的 GPU 显存设置此值",
        },
        "EmbMergeMethodSelection": {
            "level": 1,
            "label": "嵌入合并方法",
            "options": ["Mean", "Median"],
            "default": "Mean",
            "help": '选择合并面部嵌入的方法。"Mean" 平均嵌入，而 "Median" 选择中间值，对异常值提供更强的鲁棒性。',
        },
    },
    "检测器": {
        "RecognitionModelSelection": {
            "level": 1,
            "label": "识别模型",
            "options": [
                "Inswapper128ArcFace",
                "SimSwapArcFace",
                "GhostArcFace",
                "CSCSArcFace",
            ],
            "default": "Inswapper128ArcFace",
            "help": "选择用于比较面部相似度的 ArcFace 模型。",
        },
        "SimilarityTypeSelection": {
            "level": 1,
            "label": "换脸相似度类型",
            "options": ["Opal", "Pearl", "Optimal"],
            "default": "Optimal",
            "help": "选择换脸过程中面部检测和匹配的相似度计算类型。",
        },
        "DetectorModelSelection": {
            "level": 1,
            "label": "面部检测模型",
            "options": ["RetinaFace", "Yolov8", "SCRFD", "Yunet"],
            "default": "RetinaFace",
            "help": "选择用于检测输入图像或视频中面部的面部检测模型。",
        },
        "FaceTrackingEnableToggle": {
            "level": 1,
            "label": "启用面部跟踪 (ByteTrack)",
            "default": False,
            "help": "使用 ByteTrack 在帧之间保持面部身份。提高遮挡期间的稳定性并允许更低的检测阈值。",
            "exec_function": control_actions.handle_face_detector_tracking_reset,  # Added reset helper
            "exec_function_args": [],
        },
        "DetectorScoreSlider": {
            "level": 1,
            "label": "检测分数",
            "min_value": "1",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "help": "设置面部检测的置信度分数阈值。值越高确保检测更自信，但可能会错过一些面部。",
        },
        "FaceDetectionIntervalSlider": {
            "level": 1,
            "label": "检测间隔（帧）",
            "min_value": "1",
            "max_value": "30",
            "default": "1",
            "step": 1,
            "help": "多久运行一次完整的面部检测器。值越高提高 FPS，但可能会丢失快速移动的面部。1 = 每帧检测（最慢）。",
        },
        "MaxFacesToDetectSlider": {
            "level": 1,
            "label": "最大检测面部数量",
            "min_value": "1",
            "max_value": "50",
            "default": "20",
            "step": 1,
            "help": "设置一帧中检测的最大面部数量",
        },
        "AutoRotationToggle": {
            "level": 1,
            "label": "自动旋转",
            "default": False,
            "help": "自动旋转输入以检测各种方向的面部。",
        },
        "ManualRotationEnableToggle": {
            "level": 1,
            "label": "手动旋转",
            "default": False,
            "help": "旋转面部检测器以更好地检测不同角度的面部。",
        },
        "ManualRotationAngleSlider": {
            "level": 2,
            "label": "旋转角度",
            "min_value": "0",
            "max_value": "270",
            "default": "0",
            "step": 90,
            "parentToggle": "ManualRotationEnableToggle",
            "requiredToggleValue": True,
            "help": "设置为输入面部角度，以帮助处理躺下/倒立等情况。角度按顺时针读取。",
        },
        "LandmarkDetectToggle": {
            "level": 1,
            "label": "启用 landmark 检测",
            "default": False,
            "help": "启用或禁用面部 landmark 检测，用于细化面部对齐。",
            "exec_function": control_actions.handle_landmark_state_change,
            "exec_function_args": ["LandmarkDetectToggle"],
        },
        "LandmarkDetectModelSelection": {
            "level": 2,
            "label": "Landmark 检测模型",
            "options": ["5", "68", "3d68", "98", "106", "203", "478"],
            "default": "203",
            "parentToggle": "LandmarkDetectToggle",
            "requiredToggleValue": True,
            "help": "选择 landmark 检测模型，不同模型检测不同数量的面部 landmark。",
            "exec_function": control_actions.handle_landmark_model_selection_change,
            "exec_function_args": ["LandmarkDetectModelSelection"],
        },
        "LandmarkDetectScoreSlider": {
            "level": 2,
            "label": "Landmark 检测分数",
            "min_value": "1",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentToggle": "LandmarkDetectToggle",
            "requiredToggleValue": True,
            "help": "设置面部 landmark 检测的置信度分数阈值。",
        },
        "DetectFromPointsToggle": {
            "level": 2,
            "label": "从点检测",
            "default": False,
            "parentToggle": "LandmarkDetectToggle",
            "requiredToggleValue": True,
            "help": "启用从指定 landmark 点检测面部。",
        },
        "LandmarkMeanEyesToggle": {
            "level": 2,
            "label": "使用平均眼睛",
            "default": False,
            "parentToggle": "LandmarkDetectToggle",
            "requiredToggleValue": True,
            "help": "通过平均眼睛的多个点来增加稳定性（推荐用于 203/478 模型）。",
        },
        "ShowLandmarksEnableToggle": {
            "level": 1,
            "label": "显示 Landmarks",
            "default": False,
            "help": "实时显示 Landmarks。",
        },
        "ShowAllDetectedFacesBBoxToggle": {
            "level": 1,
            "label": "显示边界框",
            "default": False,
            "help": "在帧中为所有检测到的面部绘制边界框",
        },
    },
    "帧增强器": {
        "FrameEnhancerEnableToggle": {
            "level": 1,
            "label": "启用帧增强器",
            "default": False,
            "help": "启用视频输入的帧增强以提高视觉质量。",
            "exec_function": control_actions.handle_frame_enhancer_state_change,
            "exec_function_args": ["FrameEnhancerEnableToggle"],
        },
        "FrameEnhancerTypeSelection": {
            "level": 2,
            "label": "帧增强器类型",
            "options": [
                "RealEsrgan-x2-Plus",
                "RealEsrgan-x4-Plus",
                "RealEsr-General-x4v3",
                "BSRGan-x2",
                "BSRGan-x4",
                "UltraSharp-x4",
                "UltraMix-x4",
                "DDColor-Artistic",
                "DDColor",
                "DeOldify-Artistic",
                "DeOldify-Stable",
                "DeOldify-Video",
            ],
            "default": "RealEsrgan-x2-Plus",
            "parentToggle": "FrameEnhancerEnableToggle",
            "requiredToggleValue": True,
            "help": "根据内容和分辨率要求选择要应用的帧增强类型。",
            "exec_function": control_actions.handle_enhancer_model_selection_change,
            "exec_function_args": ["FrameEnhancerTypeSelection"],
        },
        "FrameEnhancerBlendSlider": {
            "level": 2,
            "label": "混合",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FrameEnhancerEnableToggle",
            "requiredToggleValue": True,
            "help": "将增强结果混合回原始帧。",
        },
    },
    "网络摄像头和虚拟摄像头设置": {
        "WebcamMaxNoSelection": {
            "level": 2,
            "label": "网络摄像头最大数量",
            "options": ["1", "2", "3", "4", "5", "6"],
            "default": "1",
            "help": "选择允许用于换脸的最大网络摄像头流数量。",
        },
        "WebcamBackendSelection": {
            "level": 2,
            "label": "网络摄像头后端",
            "options": ["Default", "DirectShow", "MSMF", "V4L", "V4L2", "GSTREAMER"],
            "default": "Default",
            "help": "选择访问网络摄像头输入的后端。",
        },
        "WebcamMaxResSelection": {
            "level": 2,
            "label": "网络摄像头分辨率",
            "options": [
                "480x360",
                "640x480",
                "1280x720",
                "1920x1080",
                "2560x1440",
                "3840x2160",
            ],
            "default": "1280x720",
            "help": "选择网络摄像头输入的最大分辨率。",
        },
        "WebCamMaxFPSSelection": {
            "level": 2,
            "label": "网络摄像头 FPS",
            "options": ["23", "30", "60"],
            "default": "30",
            "help": "设置网络摄像头输入的最大帧率（FPS）。",
        },
        "SendVirtCamFramesEnableToggle": {
            "level": 1,
            "label": "发送帧到虚拟摄像头",
            "default": False,
            "help": "将换脸后的视频/网络摄像头输出发送到虚拟摄像头，以便在外部应用程序中使用",
            "exec_function": control_actions.toggle_virtualcam,
            "exec_function_args": [],
        },
        "VirtCamBackendSelection": {
            "level": 1,
            "label": "虚拟摄像头后端",
            "options": ["obs", "unitycapture"],
            "default": "obs",
            "help": "根据您设置的虚拟摄像头选择后端",
            "parentToggle": "SendVirtCamFramesEnableToggle",
            "requiredToggleValue": True,
            "exec_function": control_actions.enable_virtualcam,
            "exec_funtion_args": [],
        },
    },
    "杂项": {
        "KeepModelsAliveToggle": {
            "level": 1,
            "label": "在内存中保持加载的模型",
            "default": False,
            "help": "阻止模型在更改设置时自动卸载，仅通过 CLEAR GPU 按钮卸载。",
        },
        "TargetMediaFolderRecursiveToggle": {
            "level": 1,
            "label": "目标媒体包含子文件夹",
            "default": False,
            "help": "选择目标媒体文件夹时包含所有子文件夹中的文件",
        },
        "InputFacesFolderRecursiveToggle": {
            "level": 1,
            "label": "输入面部包含子文件夹",
            "default": False,
            "help": "选择输入面部文件夹时包含所有子文件夹中的文件",
        },
        "ImageFormatToggle": {
            "level": 1,
            "label": "以 JPG 格式保存输出图像",
            "default": False,
            "help": "将保存图像或批处理的输出图像保存为 JPG 格式而不是 PNG。",
        },
        "CommandLineDebugEnableToggle": {
            "level": 1,
            "label": "命令行信息",
            "default": False,
            "help": "在命令行中显示恢复强度和所需迭代次数 + jpeg/mpeg 信息",
        },
        "AutoSaveWorkspaceToggle": {
            "level": 1,
            "label": "自动保存工作区",
            "default": False,
            "help": "在录制结束时自动在输出文件夹中保存工作区 .json（仅录制结束时的状态）",
        },
        "AutoLoadWorkspaceToggle": {
            "level": 1,
            "label": "自动加载上次工作区",
            "default": False,
            "help": '打开应用程序时不显示"加载上次工作区"对话框，始终加载上次工作区。',
        },
        "DilatationTypeSelection": {
            "level": 1,
            "label": "遮罩扩张类型",
            "options": ["conv", "pool", "iter_pool"],
            "default": "conv",
            "help": "Max_Pool2d 更快但 conv2d 更精确（尤其是在更高的扩张值上）",
        },
    },
    "实验性设置（非常实验性，最好不要触摸）": {
        "ActivateexperimentalsettingsEnableToggle": {
            "level": 1,
            "label": "实验性设置",
            "default": False,
            "help": "启用自动颜色转移：1. 无遮罩的 Hans 测试，2. 有遮罩的 Hans 测试，3. 无遮罩的 DFL 方法，4. DFL 原始方法。",
        },
        "AnalyseImageEnableToggle": {
            "level": 2,
            "label": "分析图像",
            "default": False,
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "图像分析",
        },
        #        'DFLXSegBGEnableToggle': {
        #            'level': 2,
        #            'label': 'Xseg 2 Background',
        #            'default': False,
        #            'parentToggle': 'ActivateexperimentalsettingsEnableToggle',
        #            'requiredToggleValue': True,
        #            'help': 'Enable second XSeg Mask for Inside the Face. not working well atm. (uses Faceparser on swap)'
        #        },
        #        'OccluderMaskBgSlider': {
        #            'level': 3,
        #            'label': 'Xseg 2 Background Adjust',
        #            'min_value': '-40',
        #            'max_value': '40',
        #            'default': '-10',
        #            'step': 1,
        #            'parentToggle': 'DFLXSegBGEnableToggle',
        #            'requiredToggleValue': True,
        #            'help': 'Adjust where the second Xseg Mask gets applied.'
        #        },
        "get_cropped_face_kpsTypeSelection": {
            "level": 2,
            "label": "get cropped face kps",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！用于基本功能测试。更改必要的处理流程函数的插值类型（图像的调整大小/旋转等）。注意，影响自动恢复计算",
        },
        "original_face_128_384TypeSelection": {
            "level": 2,
            "label": "original_128_384",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！用于基本功能测试。更改必要的处理流程函数的插值类型（图像的调整大小/旋转等）。注意，影响自动恢复计算",
        },
        "original_face_512TypeSelection": {
            "level": 2,
            "label": "original_512",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！用于基本功能测试。更改必要的处理流程函数的插值类型（图像的调整大小/旋转等）。注意，影响自动恢复计算",
        },
        "UntransformTypeSelection": {
            "level": 2,
            "label": "Untransform",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！用于基本功能测试。更改必要的处理流程函数的插值类型（图像的调整大小/旋转等）。注意，影响自动恢复计算",
        },
        "ScalebackFrameTypeSelection": {
            "level": 2,
            "label": "Scaleback Frame",
            "options": ["NEAREST", "BILINEAR", "BICUBIC"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！用于基本功能测试。更改必要的处理流程函数的插值类型（图像的调整大小/旋转等）。注意，影响自动恢复计算",
        },
        "expression_faceeditor_t256TypeSelection": {
            "level": 2,
            "label": "Expression_faceeditor_t256",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！用于基本功能测试。更改必要的处理流程函数的插值类型（图像的调整大小/旋转等）。注意，影响自动恢复计算",
        },
        "expression_faceeditor_backTypeSelection": {
            "level": 2,
            "label": "Expression_faceeditor_back",
            "options": ["NEAREST", "BILINEAR"],
            "default": "BILINEAR",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！用于基本功能测试。更改必要的处理流程函数的插值类型（图像的调整大小/旋转等）。注意，影响自动恢复计算",
        },
        "block_shiftTypeSelection": {
            "level": 2,
            "label": "block shift",
            "options": ["NEAREST", "BILINEAR"],
            "default": "NEAREST",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！用于基本功能测试。更改必要的处理流程函数的插值类型（图像的调整大小/旋转等）。注意，影响自动恢复计算",
        },
        "AntialiasTypeSelection": {
            "level": 2,
            "label": "Antialias",
            "options": ["False", "True"],
            "default": "False",
            "parentToggle": "ActivateexperimentalsettingsEnableToggle",
            "requiredToggleValue": True,
            "help": "实验性！大多数时候没有视觉效果，在 rare 情况下有 minor 效果",
        },
    },
}

CAMERA_BACKENDS = {
    "Default": cv2.CAP_ANY,
    "DirectShow": cv2.CAP_DSHOW,
    "MSMF": cv2.CAP_MSMF,
    "V4L": cv2.CAP_V4L,
    "V4L2": cv2.CAP_V4L2,
    "GSTREAMER": cv2.CAP_GSTREAMER,
}
