from typing import Any
import app.ui.widgets.actions.control_actions as control_actions

# Widgets in Face Swap tab are created from this Layout
SWAPPER_LAYOUT_DATA: Any = {  # noqa: F811
    "换脸器": {
        "SwapModelSelection": {
            "level": 1,
            "label": "换脸模型",
            "options": [
                "Inswapper128",
                "InStyleSwapper256 Version A",
                "InStyleSwapper256 Version B",
                "InStyleSwapper256 Version C",
                "DeepFaceLive (DFM)",
                "SimSwap512",
                "GhostFace-v1",
                "GhostFace-v2",
                "GhostFace-v3",
                "CSCS",
            ],
            "default": "Inswapper128",
            "help": "选择用于换脸的模型。",
        },
        "SwapperResSelection": {
            "level": 2,
            "label": "换脸分辨率",
            "options": ["128", "256", "384", "512"],
            "default": "128",
            "parentSelection": "SwapModelSelection",
            "requiredSelectionValue": "Inswapper128",
            "help": "选择换脸的像素分辨率。更高的值提供更好的质量，但处理速度更慢。",
        },
        "SwapperResAutoSelectEnableToggle": {
            "level": 2,
            "label": "启用自动分辨率",
            "default": False,
            "parentSelection": "SwapModelSelection",
            "requiredSelectionValue": "Inswapper128",
            "help": "根据原始面部大小自动选择换脸分辨率（仅适用于 Inswapper）。",
        },
        "InStyleResAEnableToggle": {
            "level": 2,
            "label": "512 分辨率",
            "default": False,
            "parentSelection": "SwapModelSelection",
            "requiredSelectionValue": "InStyleSwapper256 Version A",
            "help": "类似于 Inswapper 的 512 分辨率，适用于 InStyleSwappers。",
        },
        "InStyleResBEnableToggle": {
            "level": 2,
            "label": "512 分辨率",
            "default": False,
            "parentSelection": "SwapModelSelection",
            "requiredSelectionValue": "InStyleSwapper256 Version B",
            "help": "类似于 Inswapper 的 512 分辨率，适用于 InStyleSwappers。",
        },
        "InStyleResCEnableToggle": {
            "level": 2,
            "label": "512 分辨率",
            "default": False,
            "parentSelection": "SwapModelSelection",
            "requiredSelectionValue": "InStyleSwapper256 Version C",
            "help": "类似于 Inswapper 的 512 分辨率，适用于 InStyleSwappers。",
        },
        "DFMModelSelection": {
            "level": 2,
            "label": "DFM 模型",
            "options": lambda manager: manager.get_selection_values(),
            "default": lambda manager: manager.get_default_value(),
            "parentSelection": "SwapModelSelection",
            "requiredSelectionValue": "DeepFaceLive (DFM)",
            "help": "选择要用于换脸的预训练 DeepFaceLive (DFM) 模型。",
        },
        "DFMAmpMorphSlider": {
            "level": 2,
            "label": "AMP 变形因子",
            "min_value": "1",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentSelection": "SwapModelSelection",
            "requiredSelectionValue": "DeepFaceLive (DFM)",
            "help": "DFM AMP 模型的 AMP 变形因子",
        },
        "DFMRCTColorToggle": {
            "level": 2,
            "label": "RCT 颜色转移",
            "default": False,
            "parentSelection": "SwapModelSelection",
            "requiredSelectionValue": "DeepFaceLive (DFM)",
            "help": "DFM 模型的 RCT 颜色转移",
        },
        "SimilarityThresholdSlider": {
            "level": 1,
            "label": "相似度阈值",
            "min_value": "1",
            "max_value": "100",
            "default": "60",
            "step": 1,
            "help": "设置相似度阈值，以控制检测到的面部与参考（目标）面部的相似程度。",
        },
        "PreSwapSharpnessDecimalSlider": {
            "level": 1,
            "label": "换脸前锐度 (1.0)",
            "min_value": "0.0",
            "max_value": "2.0",
            "default": "1.0",
            "step": 0.1,
            "decimals": 1,
            "help": '在换脸前锐化原始面部。有时会很有用。注意：这可能会影响"自动面部修复器"！',
        },
    },
    "换脸强度和相似度": {
        "StrengthEnableToggle": {
            "level": 1,
            "label": "强度",
            "default": False,
            "help": "应用额外的换脸迭代以增加结果的强度，这可能会提高相似度。",
        },
        "StrengthAmountSlider": {
            "level": 2,
            "label": "强度值",
            "min_value": "0",
            "max_value": "500",
            "default": "100",
            "step": 25,
            "parentToggle": "StrengthEnableToggle",
            "requiredToggleValue": True,
            "help": "最多增加 5 倍的额外换脸（500%）。200% 通常是一个好结果。设置为 0 可关闭换脸，但允许管道的其余部分应用于原始图像。",
        },
        "FaceLikenessEnableToggle": {
            "level": 1,
            "label": "面部相似度",
            "default": False,
            "help": "这是一个直接调整面部相似度的功能。",
        },
        "FaceLikenessFactorDecimalSlider": {
            "level": 2,
            "label": "相似度值",
            "min_value": "-1.00",
            "max_value": "4.00",
            "default": "0.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "FaceLikenessEnableToggle",
            "requiredToggleValue": True,
            "help": "确定源面部和目标面部之间的相似度因子。",
        },
        "FaceLikenessNormalizationEnableToggle": {
            "level": 2,
            "label": "标准化相似度",
            "default": True,
            "parentToggle": "FaceLikenessEnableToggle",
            "requiredToggleValue": True,
            "help": "保留面部特征的能量/体积。使用高相似度值时必须开启，以防止面部变得灰暗/平淡。",
        },
        "FaceKeypointsReplaceEnableToggle": {
            "level": 1,
            "label": "面部关键点替换",
            "default": False,
            "help": "调整源面部以获取目标 KPS 点",
        },
        "FaceKeypointsReplaceDecimalSlider": {
            "level": 2,
            "label": "替换值",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "0.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "FaceKeypointsReplaceEnableToggle",
            "requiredToggleValue": True,
            "help": "确定从目标面部到源面部的 KPS 转移因子。",
        },
    },
    "遮罩": {
        "MaskShowSelection": {
            "level": 1,
            "label": "遮罩视图选择",
            "options": ["swap_mask", "diff", "texture"],
            "default": "swap_mask",
            "help": "选择在\"查看面部遮罩\"中显示的遮罩。",
        },
        "BordermaskEnableToggle": {
            "level": 1,
            "label": "边框遮罩",
            "default": False,
            "help": "一个可调整底部、左侧、右侧、顶部和侧面的矩形，用于将换脸结果遮罩回原始图像。",
        },
        "BorderBottomSlider": {
            "level": 2,
            "label": "底部边框",
            "min_value": "0",
            "max_value": "100",
            "default": "10",
            "step": 1,
            "parentToggle": "BordermaskEnableToggle",
            "requiredToggleValue": True,
            "help": "一个可调整底部、左侧、右侧、顶部和侧面的矩形，用于将换脸结果遮罩回原始图像。",
        },
        "BorderLeftSlider": {
            "level": 2,
            "label": "左侧边框",
            "min_value": "0",
            "max_value": "100",
            "default": "10",
            "step": 1,
            "parentToggle": "BordermaskEnableToggle",
            "requiredToggleValue": True,
            "help": "一个可调整底部、左侧、右侧、顶部和侧面的矩形，用于将换脸结果遮罩回原始图像。",
        },
        "BorderRightSlider": {
            "level": 2,
            "label": "右侧边框",
            "min_value": "0",
            "max_value": "100",
            "default": "10",
            "step": 1,
            "parentToggle": "BordermaskEnableToggle",
            "requiredToggleValue": True,
            "help": "一个可调整底部、左侧、右侧、顶部和侧面的矩形，用于将换脸结果遮罩回原始图像。",
        },
        "BorderTopSlider": {
            "level": 2,
            "label": "顶部边框",
            "min_value": "0",
            "max_value": "100",
            "default": "10",
            "step": 1,
            "parentToggle": "BordermaskEnableToggle",
            "requiredToggleValue": True,
            "help": "一个可调整底部、左侧、右侧、顶部和侧面的矩形，用于将换脸结果遮罩回原始图像。",
        },
        "BorderBlurSlider": {
            "level": 2,
            "label": "边框模糊",
            "min_value": "0",
            "max_value": "100",
            "default": "10",
            "step": 1,
            "parentToggle": "BordermaskEnableToggle",
            "requiredToggleValue": True,
            "help": "边框遮罩混合距离。",
        },
        "ProfileAngleMaskEnableToggle": {
            "level": 1,
            "label": "侧面角度遮罩",
            "default": False,
            "help": "当头部转向时（侧面视图）自动淡化面部的远端，以隐藏扭曲。",
        },
        "ProfileAngleMaskThresholdSlider": {
            "level": 2,
            "label": "角度阈值",
            "min_value": "0",
            "max_value": "90",
            "default": "25",
            "step": 1,
            "parentToggle": "ProfileAngleMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "应用遮罩的起始角度（度）。较低的值会更早应用。",
        },
        "ProfileAngleMaskStrengthSlider": {
            "level": 2,
            "label": "淡出强度",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 5,
            "parentToggle": "ProfileAngleMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "渐变淡出的强度。",
        },
        "OccluderEnableToggle": {
            "level": 1,
            "label": "遮挡物遮罩",
            "default": False,
            "help": "允许遮挡面部的物体在换脸图像中显示。",
            "exec_function": control_actions.handle_face_mask_state_change,
            "exec_function_args": ["OccluderEnableToggle"],
        },
        "OccluderSizeSlider": {
            "level": 2,
            "label": "大小",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "OccluderEnableToggle",
            "requiredToggleValue": True,
            "help": "增大或缩小遮挡区域",
        },
        "OccluderTonguePriorityToggle": {
            "level": 2,
            "label": "舌头/嘴巴优先级",
            "default": False,
            "parentToggle": "OccluderEnableToggle",
            "requiredToggleValue": True,
            "help": "当增加遮挡物大小时，防止舌头或口腔内部物体被擦除。使用 FaceParser 保护口腔内部区域。",
        },
        "DFLXSegEnableToggle": {
            "level": 1,
            "label": "DFL XSeg 遮罩",
            "default": False,
            "help": "允许遮挡面部的物体在换脸图像中显示。",
            "exec_function": control_actions.handle_face_mask_state_change,
            "exec_function_args": ["DFLXSegEnableToggle"],
        },
        "XSegExcludeInnerMouthToggle": {
            "level": 2,
            "label": "嘴巴/嘴唇保护",
            "default": False,
            "parentToggle": "DFLXSegEnableToggle",
            "requiredToggleValue": True,
            "help": "防止 XSeg 遮罩口腔内部区域。修复将张开的嘴巴误认为障碍物的问题。",
        },
        "DFLXSegSizeSlider": {
            "level": 2,
            "label": "大小",
            "min_value": "-20",
            "max_value": "20",
            "default": "0",
            "step": 1,
            "parentToggle": "DFLXSegEnableToggle",
            "requiredToggleValue": True,
            "help": "增大或缩小遮挡区域。",
        },
        "OccluderXSegBlurSlider": {
            "level": 1,
            "label": "遮挡物/DFL XSeg 模糊",
            "min_value": "0",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "OccluderEnableToggle | DFLXSegEnableToggle",
            "requiredToggleValue": True,
            "help": "遮挡物和 XSeg 的混合值。",
        },
        "XSegMouthEnableToggle": {
            "level": 2,
            "label": "XSeg 嘴巴",
            "default": False,
            "parentToggle": "DFLXSegEnableToggle",
            "requiredToggleValue": True,
            "help": "在嘴巴区域使用第二个 XSeg 遮罩。",
        },
        "DFLXSeg2SizeSlider": {
            "level": 3,
            "label": "大小",
            "min_value": "-50",
            "max_value": "50",
            "default": "-1",
            "step": 1,
            "parentToggle": "DFLXSegEnableToggle & XSegMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "增大或缩小遮挡嘴巴区域的 XSeg 遮罩。",
        },
        "XSeg2BlurSlider": {
            "level": 3,
            "label": "模糊",
            "min_value": "0",
            "max_value": "100",
            "default": "4",
            "step": 1,
            "parentToggle": "DFLXSegEnableToggle & XSegMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "嘴巴 XSeg 遮罩的模糊效果",
        },
        "XsegMouthParserSlider": {
            "level": 3,
            "label": "嘴巴",
            "min_value": "0",
            "max_value": "30",
            "default": "2",
            "step": 1,
            "parentToggle": "DFLXSegEnableToggle & XSegMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "扩大嘴巴区域（在换脸上使用 Faceparser）",
        },
        "XsegUpperLipParserSlider": {
            "level": 3,
            "label": "上嘴唇",
            "min_value": "0",
            "max_value": "30",
            "default": "2",
            "step": 1,
            "parentToggle": "DFLXSegEnableToggle & XSegMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "扩大上嘴唇区域（在换脸上使用 Faceparser）",
        },
        "XsegLowerLipParserSlider": {
            "level": 3,
            "label": "下嘴唇",
            "min_value": "0",
            "max_value": "30",
            "default": "10",
            "step": 1,
            "parentToggle": "DFLXSegEnableToggle & XSegMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "扩大下嘴唇区域（在换脸上使用 Faceparser）",
        },
        "ClipEnableToggle": {
            "level": 1,
            "label": "文本遮罩",
            "default": False,
            "help": "使用描述来识别最终换脸图像中会出现的对象。",
            "exec_function": control_actions.handle_face_mask_state_change,
            "exec_function_args": ["ClipEnableToggle"],
        },
        "ClipText": {
            "level": 2,
            "label": "文本遮罩输入",
            "min_value": "0",
            "max_value": "1000",
            "default": "",
            "width": 130,
            "parentToggle": "ClipEnableToggle",
            "requiredToggleValue": True,
            "help": "使用方法：在框中输入单词（用逗号分隔）并按 <enter>。",
        },
        "ClipAmountSlider": {
            "level": 2,
            "label": "强度",
            "min_value": "0",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentToggle": "ClipEnableToggle",
            "requiredToggleValue": True,
            "help": "增加以增强效果。",
        },
    },
    "原始面部解析器": {
        "MouthParserStretchToggle": {
            "level": 1,
            "label": "嘴巴适配与对齐",
            "default": False,
            "help": "重新定位和缩放原始嘴巴以适应换脸，而不扭曲其形状。可以独立于面部解析器使用。",
        },
        "MouthParserStretchOriginalToggle": {
            "level": 2,
            "label": "使用原始嘴巴",
            "default": False,
            "parentToggle": "MouthParserStretchToggle",
            "requiredToggleValue": True,
            "help": "使用原始嘴巴进行适配与对齐。",
        },
        "MouthParserStretchAfterToggle": {
            "level": 2,
            "label": "在修复器后粘贴",
            "default": False,
            "parentToggle": "MouthParserStretchToggle",
            "requiredToggleValue": True,
            "help": "在修复器之后粘贴嘴巴遮罩。",
        },
        "MouthParserStretchSharpenDecimalSlider": {
            "level": 2,
            "label": "智能锐化 (USM)",
            "min_value": "0.00",
            "max_value": "5.00",
            "default": "0.00",
            "decimals": 2,
            "step": 0.10,
            "parentToggle": "MouthParserStretchToggle",
            "requiredToggleValue": True,
            "help": "对嘴巴应用边缘感知非锐化遮罩。增强牙齿和嘴唇边缘，而不会给光滑的皮肤添加噪点。",
        },
        "MouthParserStretchDecimalSlider": {
            "level": 2,
            "label": "嘴巴缩放",
            "min_value": "0.90",
            "max_value": "1.20",
            "default": "1.05",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "MouthParserStretchToggle",
            "requiredToggleValue": True,
            "help": "嘴巴缩放滑块。",
        },
        "FaceParserEnableToggle": {
            "level": 1,
            "label": "面部解析器遮罩",
            "default": False,
            "help": "允许原始图像中未处理的背景在最终换脸中显示。",
            "exec_function": control_actions.handle_face_mask_state_change,
            "exec_function_args": ["FaceParserEnableToggle"],
        },
        "FaceParserEndToggle": {
            "level": 2,
            "label": "在管道末尾解析",
            "default": False,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "在管道末尾运行解析器遮罩。",
        },
        "MouthParserInsideToggle": {
            "level": 2,
            "label": "嘴巴内部开关",
            "default": True,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "保持解析在嘴巴内部（值超过 1 会慢慢与换脸嘴巴重叠）。",
        },
        "BackgroundParserSlider": {
            "level": 2,
            "label": "背景",
            "min_value": "-50",
            "max_value": "50",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "负值/正值会缩小和扩大遮罩。",
        },
        "FaceParserSlider": {
            "level": 2,
            "label": "面部",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个面部。",
        },
        "LeftEyebrowParserSlider": {
            "level": 2,
            "label": "左眉毛",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个左眉毛。",
        },
        "RightEyebrowParserSlider": {
            "level": 2,
            "label": "右眉毛",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个右眉毛。",
        },
        "LeftEyeParserSlider": {
            "level": 2,
            "label": "左眼",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个左眼。",
        },
        "RightEyeParserSlider": {
            "level": 2,
            "label": "右眼",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个右眼。",
        },
        "EyeGlassesParserSlider": {
            "level": 2,
            "label": "眼镜",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个眼镜。",
        },
        "NoseParserSlider": {
            "level": 2,
            "label": "鼻子",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个鼻子。",
        },
        "MouthParserSlider": {
            "level": 2,
            "label": "嘴巴",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩嘴巴内部，包括舌头。",
        },
        "UpperLipParserSlider": {
            "level": 2,
            "label": "上嘴唇",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个上嘴唇。",
        },
        "LowerLipParserSlider": {
            "level": 2,
            "label": "下嘴唇",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个下嘴唇。",
        },
        "NeckParserSlider": {
            "level": 2,
            "label": "脖子",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个脖子。",
        },
        "HairParserSlider": {
            "level": 2,
            "label": "头发",
            "min_value": "0",
            "max_value": "30",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩大小。遮罩整个头发。",
        },
        "BackgroundBlurParserSlider": {
            "level": 2,
            "label": "背景模糊",
            "min_value": "0",
            "max_value": "100",
            "default": "5",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "背景解析器的混合值",
        },
        "FaceBlurParserSlider": {
            "level": 2,
            "label": "面部模糊",
            "min_value": "0",
            "max_value": "100",
            "default": "5",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "面部解析器的混合值",
        },
        "FaceParserBlendSlider": {
            "level": 2,
            "label": "面部混合",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "FaceParserEnableToggle",
            "requiredToggleValue": True,
            "help": "面部解析器的混合值",
        },
        "RestoreEyesEnableToggle": {
            "level": 1,
            "label": "恢复眼睛",
            "default": False,
            "help": "从原始面部恢复眼睛。",
        },
        "RestoreEyesBlendAmountSlider": {
            "level": 2,
            "label": "眼睛混合量",
            "min_value": "1",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentToggle": "RestoreEyesEnableToggle",
            "requiredToggleValue": True,
            "help": "增加此值以显示更多交换的眼睛。减少此值以显示更多原始眼睛。",
        },
        "RestoreEyesSizeFactorDecimalSlider": {
            "level": 2,
            "label": "眼睛大小因子",
            "min_value": "2.0",
            "max_value": "4.0",
            "default": "3.0",
            "decimals": 1,
            "step": 0.5,
            "parentToggle": "RestoreEyesEnableToggle",
            "requiredToggleValue": True,
            "help": "当交换的面部在画面中缩小时，减少此值。",
        },
        "RestoreEyesFeatherBlendSlider": {
            "level": 2,
            "label": "眼睛羽化混合",
            "min_value": "1",
            "max_value": "100",
            "default": "10",
            "step": 1,
            "parentToggle": "RestoreEyesEnableToggle",
            "requiredToggleValue": True,
            "help": "调整眼睛边界的混合。增加此值以显示更多原始眼睛。减少此值以显示更多交换的眼睛。",
        },
        "RestoreXEyesRadiusFactorDecimalSlider": {
            "level": 2,
            "label": "X眼睛半径因子",
            "min_value": "0.3",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "RestoreEyesEnableToggle",
            "requiredToggleValue": True,
            "help": "这些参数决定遮罩的形状。如果两者都等于1.0，遮罩将是圆形的。如果其中任何一个大于或小于1.0，遮罩将变为椭圆形，沿相应方向拉伸或收缩。",
        },
        "RestoreYEyesRadiusFactorDecimalSlider": {
            "level": 2,
            "label": "Y眼睛半径因子",
            "min_value": "0.3",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "RestoreEyesEnableToggle",
            "requiredToggleValue": True,
            "help": "这些参数决定遮罩的形状。如果两者都等于1.0，遮罩将是圆形的。如果其中任何一个大于或小于1.0，遮罩将变为椭圆形，沿相应方向拉伸或收缩。",
        },
        "RestoreXEyesOffsetSlider": {
            "level": 2,
            "label": "X眼睛偏移",
            "min_value": "-300",
            "max_value": "300",
            "default": "0",
            "step": 1,
            "parentToggle": "RestoreEyesEnableToggle",
            "requiredToggleValue": True,
            "help": "调整恢复眼睛的X偏移",
        },
        "RestoreYEyesOffsetSlider": {
            "level": 2,
            "label": "Y眼睛偏移",
            "min_value": "-300",
            "max_value": "300",
            "default": "0",
            "step": 1,
            "parentToggle": "RestoreEyesEnableToggle",
            "requiredToggleValue": True,
            "help": "调整恢复眼睛的Y偏移",
        },
        "RestoreEyesSpacingOffsetSlider": {
            "level": 2,
            "label": "眼睛间距偏移",
            "min_value": "-200",
            "max_value": "200",
            "default": "0",
            "step": 1,
            "parentToggle": "RestoreEyesEnableToggle",
            "requiredToggleValue": True,
            "help": "调整恢复眼睛之间的间距",
        },
        "RestoreMouthEnableToggle": {
            "level": 1,
            "label": "恢复嘴巴",
            "default": False,
            "help": "从原始面部恢复嘴巴。",
        },
        "RestoreMouthBlendAmountSlider": {
            "level": 2,
            "label": "嘴巴混合量",
            "min_value": "1",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentToggle": "RestoreMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "增加此值以显示更多交换的嘴巴。减少此值以显示更多原始嘴巴。",
        },
        "RestoreMouthSizeFactorSlider": {
            "level": 2,
            "label": "嘴巴大小因子",
            "min_value": "5",
            "max_value": "60",
            "default": "25",
            "step": 5,
            "parentToggle": "RestoreMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "当交换的面部在画面中缩小时，增加此值。",
        },
        "RestoreMouthFeatherBlendSlider": {
            "level": 2,
            "label": "嘴巴羽化混合",
            "min_value": "1",
            "max_value": "100",
            "default": "10",
            "step": 1,
            "parentToggle": "RestoreMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "调整嘴巴混合的边界。增加此值以显示更多原始嘴巴。减少此值以显示更多交换的嘴巴。",
        },
        "RestoreXMouthRadiusFactorDecimalSlider": {
            "level": 2,
            "label": "X嘴巴半径因子",
            "min_value": "0.3",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "RestoreMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "这些参数决定遮罩的形状。如果两者都等于1.0，遮罩将是圆形的。如果其中任何一个大于或小于1.0，遮罩将变为椭圆形，沿相应方向拉伸或收缩。",
        },
        "RestoreYMouthRadiusFactorDecimalSlider": {
            "level": 2,
            "label": "Y嘴巴半径因子",
            "min_value": "0.3",
            "max_value": "3.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "RestoreMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "这些参数决定遮罩的形状。如果两者都等于1.0，遮罩将是圆形的。如果其中任何一个大于或小于1.0，遮罩将变为椭圆形，沿相应方向拉伸或收缩。",
        },
        "RestoreXMouthOffsetSlider": {
            "level": 2,
            "label": "X嘴巴偏移",
            "min_value": "-300",
            "max_value": "300",
            "default": "0",
            "step": 1,
            "parentToggle": "RestoreMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "调整恢复嘴巴的X偏移",
        },
        "RestoreYMouthOffsetSlider": {
            "level": 2,
            "label": "Y嘴巴偏移",
            "min_value": "-300",
            "max_value": "300",
            "default": "0",
            "step": 1,
            "parentToggle": "RestoreMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "调整恢复嘴巴的Y偏移",
        },
        "RestoreEyesMouthBlurSlider": {
            "level": 1,
            "label": "眼睛/嘴巴模糊",
            "min_value": "0",
            "max_value": "50",
            "default": "0",
            "step": 1,
            "parentToggle": "RestoreEyesEnableToggle | RestoreMouthEnableToggle",
            "requiredToggleValue": True,
            "help": "调整遮罩边界的模糊度。",
        },
    },
    "纹理和颜色": {
        "DifferencingEnableToggle": {
            "level": 1,
            "label": "差异处理",
            "default": False,
            "help": "在交换和原始图像之间进行差异处理。高级差异模型，对像素之间的差异进行加权。",
        },
        "DifferencingLowerLimitThreshSlider": {
            "level": 2,
            "label": "差异下限",
            "min_value": "0",
            "max_value": "100",
            "default": "30",
            "step": 1,
            "parentToggle": "DifferencingEnableToggle",
            "requiredToggleValue": True,
            "help": '定义差异遮罩的下限。使用 "mask show -> diff" 检查 "View Face Mask" 以查看效果。',
        },
        "DifferencingUpperLimitThreshSlider": {
            "level": 2,
            "label": "差异上限",
            "min_value": "0",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentToggle": "DifferencingEnableToggle",
            "requiredToggleValue": True,
            "help": '定义差异遮罩的上限。使用 "mask show -> diff" 检查 "View Face Mask" 以查看效果。',
        },
        "DifferencingMiddleLimitValueSlider": {
            "level": 2,
            "label": "下限强度",
            "min_value": "0",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentToggle": "DifferencingEnableToggle",
            "requiredToggleValue": True,
            "help": '定义在转移遮罩中 "Difference Lower Limit" 以下的像素在交换和原始图像之间的混合。使用 "mask show -> diff" 检查 "View Face Mask" 以查看效果。',
        },
        "DifferencingUpperLimitValueSlider": {
            "level": 2,
            "label": "上限强度",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "DifferencingEnableToggle",
            "requiredToggleValue": True,
            "help": '定义在转移遮罩中 "Difference Upper Limit" 以上的像素在交换和原始图像之间的混合。使用 "mask show -> diff" 检查 "View Face Mask" 以查看效果。',
        },
        "DifferencingBlendAmountSlider": {
            "level": 2,
            "label": "遮罩模糊量",
            "min_value": "0",
            "max_value": "100",
            "default": "16",
            "step": 1,
            "parentToggle": "DifferencingEnableToggle",
            "requiredToggleValue": True,
            "help": "遮罩模糊以实现更平滑的过渡",
        },
        "TransferTextureEnableToggle": {
            "level": 1,
            "label": "转移纹理",
            "default": False,
            "help": "启用纹理转移",
        },
        "TransferTextureModeEnableToggle": {
            "level": 2,
            "label": "模式 2",
            "default": False,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "梯度幅度计算的不同值，有时效果更好，但有时会在面部产生过多条纹",
        },
        "TransferTextureBlendAmountSlider": {
            "level": 2,
            "label": "纹理强度",
            "min_value": "0",
            "max_value": "100",
            "default": "30",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "定义纹理转移的应用强度",
        },
        "TransferTexturePreGammaDecimalSlider": {
            "level": 2,
            "label": "纹理伽马调整",
            "min_value": "0.00",
            "max_value": "2.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "调整有时可能会有好处。原始面部的伽马调整用于纹理转移",
        },
        "TransferTexturePreContrastDecimalSlider": {
            "level": 2,
            "label": "纹理对比度调整",
            "min_value": "0.00",
            "max_value": "2.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "调整有时可能会有好处。原始面部的对比度调整用于纹理转移",
        },
        "TransferTextureClaheEnableToggle": {
            "level": 2,
            "label": "CLAHE",
            "default": False,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "用于一些额外效果。（对比度受限的自适应直方图均衡化）。增强局部对比度同时防止噪声过度放大。小心使用，会改变颜色动态。",
        },
        "TransferTextureClipLimitDecimalSlider": {
            "level": 3,
            "label": "CLAHE 限制",
            "min_value": "0.0",
            "max_value": "5.0",
            "default": "1.0",
            "decimals": 1,
            "step": 0.1,
            "parentToggle": "TransferTextureEnableToggle & TransferTextureClaheEnableToggle",
            "requiredToggleValue": True,
            "help": "CLAHE 的裁剪限制",
        },
        "TransferTextureAlphaClaheDecimalSlider": {
            "level": 3,
            "label": "CLAHE 混合",
            "min_value": "0.00",
            "max_value": "1.00",
            "default": "0.40",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "TransferTextureEnableToggle & TransferTextureClaheEnableToggle",
            "requiredToggleValue": True,
            "help": "较低的混合值可增加纹理强度而不会使颜色过于极端",
        },
        "ExcludeOriginalVGGMaskEnableToggle": {
            "level": 2,
            "label": "VGG 遮罩排除",
            "default": False,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "使用 VGG 模型的原始排除遮罩（无下限/上限/强度操作）",
        },
        "TextureUpperLimitSlider": {
            "level": 3,
            "label": "上限",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeOriginalVGGMaskEnableToggle",
            "requiredToggleValue": True,
            "help": '定义在转移遮罩中 "Face Features Upper Limit" 以上部分的强度。使用 "mask show -> texture" 检查 "View Face Mask" 以查看效果。',
        },
        "TextureBlendAmountSlider": {
            "level": 3,
            "label": "VGG 遮罩模糊量",
            "min_value": "0",
            "max_value": "20",
            "default": "10",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeOriginalVGGMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "VGG 遮罩模糊量",
        },
        "ExcludeVGGMaskEnableToggle": {
            "level": 3,
            "label": "VGG 遮罩操作",
            "default": False,
            "parentToggle": "TransferTextureEnableToggle & ExcludeOriginalVGGMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "使用 VGG 模型和下限/上限/强度的排除遮罩",
        },
        #'ExcludeVGGMaskSmoothEnableToggle': {
        #    'level': 3,
        #    'label': 'VGG Mask Smooth Mode',
        #    'default': False,
        #    'parentToggle': 'TransferTextureEnableToggle & ExcludeOriginalVGGMaskEnableToggle',
        #    'requiredToggleValue': True,
        #    'help': '.'
        # },
        "VGGMaskThresholdSlider": {
            "level": 3,
            "label": "阈值",
            "min_value": "0",
            "max_value": "100",
            "default": "35",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeOriginalVGGMaskEnableToggle & ExcludeVGGMaskEnableToggle",
            "requiredToggleValue": True,
            "help": '定义 VGG 转移遮罩的限制。使用 "mask show -> texture" 检查 "View Face Mask" 以查看效果。',
        },
        #'VGGMaskSoftnessSlider': {
        #    'level': 3,
        #    'label': 'Softness',
        #    'min_value': '0',
        #    'max_value': '100',
        #    'default': '50',
        #    'step': 1,
        #    'parentToggle': 'TransferTextureEnableToggle & ExcludeOriginalVGGMaskEnableToggle & ExcludeVGGMaskEnableToggle',
        #    'requiredToggleValue': True,
        #    'help': 'Defines upper Limit for transfer mask. Check "View Face Mask" with "mask show -> texture" to see effect.'
        # },
        #'VGGMaskGammaSlider': {
        #    'level': 3,
        #    'label': 'Gamma',
        #    'min_value': '0',
        #    'max_value': '100',
        #    'default': '0',
        #    'step': 1,
        #    'parentToggle': 'TransferTextureEnableToggle & ExcludeOriginalVGGMaskEnableToggle & ExcludeVGGMaskEnableToggle',
        #    'requiredToggleValue': True,
        #    'help': 'Defines the strenght of parts under "Face Features Lower Limit" in transfer mask. Check "View Face Mask" with "mask show -> texture" to see effect.'
        # },
        "ExcludeMaskEnableToggle": {
            "level": 2,
            "label": "遮罩特征排除",
            "default": False,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "从纹理转移中排除面部部分，并在那里使用原始交换。可与 VGG 遮罩结合使用",
        },
        "FaceParserTextureSlider": {
            "level": 3,
            "label": "面部混合",
            "min_value": "0",
            "max_value": "10",
            "default": "0",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "面部其余部分（无特征）的混合量",
        },
        "FaceParserBlendTextureSlider": {
            "level": 3,
            "label": "排除特征混合",
            "min_value": "-100",
            "max_value": "0",
            "default": "0",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "排除特征区域的混合量",
        },
        "EyebrowParserTextureSlider": {
            "level": 3,
            "label": "眉毛",
            "min_value": "-20",
            "max_value": "20",
            "default": "1",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "排除面部部分（眼睛、眉毛、鼻子、嘴巴、嘴唇、脖子），0=使用整个面部，1=不包括部分，1+=增加部分大小。大多数情况下应该是 1/1+。在低质量/有伪影的目标上尝试 0",
        },
        "EyeParserTextureSlider": {
            "level": 3,
            "label": "眼睛",
            "min_value": "-20",
            "max_value": "20",
            "default": "1",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "排除面部部分（眼睛、眉毛、鼻子、嘴巴、嘴唇、脖子），0=使用整个面部，1=不包括部分，1+=增加部分大小。大多数情况下应该是 1/1+。在低质量/有伪影的目标上尝试 0",
        },
        "NoseParserTextureSlider": {
            "level": 3,
            "label": "鼻子",
            "min_value": "-20",
            "max_value": "20",
            "default": "1",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "排除面部部分（眼睛、眉毛、鼻子、嘴巴、嘴唇、脖子），0=使用整个面部，1=不包括部分，1+=增加部分大小。大多数情况下应该是 1/1+。在低质量/有伪影的目标上尝试 0",
        },
        "MouthParserTextureSlider": {
            "level": 3,
            "label": "嘴巴",
            "min_value": "-20",
            "max_value": "20",
            "default": "1",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "排除面部部分（眼睛、眉毛、鼻子、嘴巴、嘴唇、脖子），0=使用整个面部，1=不包括部分，1+=增加部分大小。大多数情况下应该是 1/1+。在低质量/有伪影的目标上尝试 0",
        },
        "NeckParserTextureSlider": {
            "level": 3,
            "label": "脖子",
            "min_value": "-20",
            "max_value": "20",
            "default": "1",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & ExcludeMaskEnableToggle",
            "requiredToggleValue": True,
            "help": "排除面部部分（眼睛、眉毛、鼻子、嘴巴、嘴唇、脖子），0=使用整个面部，1=不包括部分，1+=增加部分大小。大多数情况下应该是 1/1+。在低质量/有伪影的目标上尝试 0",
        },
        "FaceParserBlurTextureSlider": {
            "level": 2,
            "label": "纹理遮罩模糊",
            "min_value": "0",
            "max_value": "20",
            "default": "4",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "排除区域边缘的遮罩模糊。",
        },
        "BgExcludeEnableToggle": {
            "level": 2,
            "label": "背景排除",
            "default": False,
            "parentToggle": "TransferTextureEnableToggle",
            "requiredToggleValue": True,
            "help": "纹理转移遮罩的背景减少，当 xseg > 0 时有用",
        },
        "BackgroundParserTextureSlider": {
            "level": 3,
            "label": "背景",
            "min_value": "-20",
            "max_value": "0",
            "default": "0",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & BgExcludeEnableToggle",
            "requiredToggleValue": True,
            "help": "基于原始面部的 XSEG 模型和交换面部的面部解析器背景进行背景减少",
        },
        "BGExcludeBlurAmountSlider": {
            "level": 3,
            "label": "背景模糊",
            "min_value": "0",
            "max_value": "50",
            "default": "0",
            "step": 1,
            "parentToggle": "TransferTextureEnableToggle & BgExcludeEnableToggle",
            "requiredToggleValue": True,
            "help": "基于原始面部的面部解析器模型进行背景减少",
        },
        "AutoColorEnableToggle": {
            "level": 1,
            "label": "自动颜色转移",
            "default": False,
            "help": "启用自动颜色转移：1. Hans 测试（无遮罩），2. Hans 测试（有遮罩），3. DFL 方法（无遮罩），4. DFL 原始方法。",
        },
        "AutoColorTransferTypeSelection": {
            "level": 2,
            "label": "转移类型",
            "options": ["Test", "Test_Mask", "DFL_Test", "DFL_Orig"],
            "default": "Test",
            "parentToggle": "AutoColorEnableToggle",
            "requiredToggleValue": True,
            "help": "选择自动颜色转移方法类型。Hans 方法有时可能会产生一些伪影。",
        },
        "AutoColorBlendAmountSlider": {
            "level": 2,
            "label": "混合量",
            "min_value": "0",
            "max_value": "100",
            "default": "80",
            "step": 5,
            "parentToggle": "AutoColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整自动颜色转移的混合量",
        },
        "EndingColorTransferEnableToggle": {
            "level": 1,
            "label": "启用结束颜色转移",
            "default": False,
            "help": "在面部恢复后启用最终颜色转移通道，以匹配原始肤色。",
        },
        "EndingColorTransferTypeSelection": {
            "level": 2,
            "label": "结束转移类型",
            "options": ["Test", "Test_Mask", "DFL_Test", "DFL_Orig"],
            "default": "Test",
            "parentToggle": "EndingColorTransferEnableToggle",
            "requiredToggleValue": True,
            "help": "选择最终通道的颜色转移算法。",
        },
        "EndingColorBlendAmountSlider": {
            "level": 2,
            "label": "结束混合量",
            "min_value": "0",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "EndingColorTransferEnableToggle",
            "requiredToggleValue": True,
            "help": "结束颜色转移的强度（0-100%）。",
        },
        "ColorEnableToggle": {
            "level": 1,
            "label": "颜色调整",
            "default": False,
            "help": "微调交换的 RGB 颜色值。",
        },
        "ColorRedSlider": {
            "level": 2,
            "label": "红色",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整红色通道",
        },
        "ColorGreenSlider": {
            "level": 2,
            "label": "绿色",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整绿色通道",
        },
        "ColorBlueSlider": {
            "level": 2,
            "label": "蓝色",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整蓝色通道",
        },
        "ColorBrightnessDecimalSlider": {
            "level": 2,
            "label": "亮度",
            "min_value": "0.00",
            "max_value": "3.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整亮度",
        },
        "ColorContrastDecimalSlider": {
            "level": 2,
            "label": "对比度",
            "min_value": "0.00",
            "max_value": "3.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整对比度",
        },
        "ColorSaturationDecimalSlider": {
            "level": 2,
            "label": "饱和度",
            "min_value": "0.00",
            "max_value": "3.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整饱和度",
        },
        "ColorSharpnessDecimalSlider": {
            "level": 2,
            "label": "锐度",
            "min_value": "0.0",
            "max_value": "20.0",
            "default": "0.0",
            "decimals": 1,
            "step": 0.5,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整锐度",
        },
        "ColorHueDecimalSlider": {
            "level": 2,
            "label": "色调",
            "min_value": "-0.50",
            "max_value": "0.50",
            "default": "0.00",
            "decimals": 2,
            "step": 0.01,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整色调",
        },
        "ColorGammaDecimalSlider": {
            "level": 2,
            "label": "伽马",
            "min_value": "0.00",
            "max_value": "3.00",
            "default": "1.00",
            "decimals": 2,
            "step": 0.05,
            "parentToggle": "ColorEnableToggle",
            "requiredToggleValue": True,
            "help": "调整伽马",
        },
        "ColorNoiseDecimalSlider": {
            "level": 1,
            "label": "噪点",
            "min_value": "0.00",
            "max_value": "20.00",
            "default": "0.00",
            "step": 1.00,
            "decimals": 2,
            "help": "向交换的面部添加噪点。",
        },
        "JPEGCompressionEnableToggle": {
            "level": 1,
            "label": "JPEG 压缩",
            "default": False,
            "help": "向交换的面部应用 JPEG 压缩以使输出更加真实",
        },
        "JPEGCompressionAmountSlider": {
            "level": 2,
            "label": "压缩",
            "min_value": "1",
            "max_value": "100",
            "default": "60",
            "step": 1,
            "parentToggle": "JPEGCompressionEnableToggle",
            "requiredToggleValue": True,
            "help": "调整 JPEG 压缩量",
        },
        "JPEGCompressionBlendSlider": {
            "level": 2,
            "label": "混合",
            "min_value": "1",
            "max_value": "100",
            "default": "100",
            "step": 1,
            "parentToggle": "JPEGCompressionEnableToggle",
            "requiredToggleValue": True,
            "help": "JPEG 压缩的混合量",
        },
        "BlockShiftEnableToggle": {
            "level": 1,
            "label": "MPEG 压缩",
            "default": False,
            "help": "应用类似 MPEG 压缩的块移位效果",
        },
        "BlockShiftAmountSlider": {
            "level": 2,
            "label": "块大小",
            "min_value": "1",
            "max_value": "8",
            "default": "4",
            "step": 1,
            "parentToggle": "BlockShiftEnableToggle",
            "requiredToggleValue": True,
            "help": "（像素）块的大小",
        },
        "BlockShiftMaxAmountSlider": {
            "level": 2,
            "label": "最大移位",
            "min_value": "1",
            "max_value": "8",
            "default": "2",
            "step": 1,
            "parentToggle": "BlockShiftEnableToggle",
            "requiredToggleValue": True,
            "help": "每个块的最大移位",
        },
        "BlockShiftBlendAmountSlider": {
            "level": 2,
            "label": "混合量",
            "min_value": "1",
            "max_value": "100",
            "default": "50",
            "step": 1,
            "parentToggle": "BlockShiftEnableToggle",
            "requiredToggleValue": True,
            "help": "MPEG 压缩效果的混合量",
        },
    },
    "面部 Landmarks 校正": {
        "FaceAdjEnableToggle": {
            "level": 1,
            "label": "面部调整",
            "default": False,
            "help": "这是一个实验性功能，用于对检测器找到的面部 landmarks 进行直接调整。还有一个选项可以调整交换面部的比例。",
        },
        "KpsXSlider": {
            "level": 2,
            "label": "关键点 X 轴",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "调整 X 轴上的关键点",
        },
        "KpsYSlider": {
            "level": 2,
            "label": "关键点 Y 轴",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "调整 Y 轴上的关键点",
        },
        "KpsScaleSlider": {
            "level": 2,
            "label": "关键点比例",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "增大和缩小检测点距离。",
        },
        "FaceScaleAmountSlider": {
            "level": 2,
            "label": "面部比例调整",
            "min_value": "-20",
            "max_value": "20",
            "default": "0",
            "step": 1,
            "parentToggle": "FaceAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "调整交换面部的比例",
        },
        "LandmarksPositionAdjEnableToggle": {
            "level": 1,
            "label": "5 - 关键点调整",
            "default": False,
            "help": "这是一个实验性功能，用于对检测器找到的面部 landmarks 位置进行直接调整。",
        },
        "EyeLeftXAmountSlider": {
            "level": 2,
            "label": "左眼:   X",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "调整左眼的 X 位置",
        },
        "EyeLeftYAmountSlider": {
            "level": 2,
            "label": "左眼:   Y",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "上下移动左眼检测点。",
        },
        "EyeRightXAmountSlider": {
            "level": 2,
            "label": "右眼:   X",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "左右移动右眼检测点。",
        },
        "EyeRightYAmountSlider": {
            "level": 2,
            "label": "右眼:   Y",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "上下移动右眼检测点。",
        },
        "NoseXAmountSlider": {
            "level": 2,
            "label": "鼻子:   X",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "左右移动鼻子检测点。",
        },
        "NoseYAmountSlider": {
            "level": 2,
            "label": "鼻子:   Y",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "上下移动鼻子检测点。",
        },
        "MouthLeftXAmountSlider": {
            "level": 2,
            "label": "左嘴:   X",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "调整左嘴的 X 位置",
        },
        "MouthLeftYAmountSlider": {
            "level": 2,
            "label": "左嘴:   Y",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "上下移动左嘴检测点。",
        },
        "MouthRightXAmountSlider": {
            "level": 2,
            "label": "右嘴:   X",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "左右移动右嘴检测点。",
        },
        "MouthRightYAmountSlider": {
            "level": 2,
            "label": "右嘴:   Y",
            "min_value": "-100",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "parentToggle": "LandmarksPositionAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "上下移动右嘴检测点。",
        },
    },
    "Blend Adjustments": {
        "FinalBlendAdjEnableToggle": {
            "level": 1,
            "label": "最终混合",
            "default": False,
            "help": "在处理流程结束时进行混合。",
        },
        "FinalBlendAmountSlider": {
            "level": 2,
            "label": "最终混合量",
            "min_value": "1",
            "max_value": "100",
            "default": "1",
            "step": 1,
            "parentToggle": "FinalBlendAdjEnableToggle",
            "requiredToggleValue": True,
            "help": "调整最终混合值。",
        },
        "OverallMaskBlendAmountSlider": {
            "level": 1,
            "label": "整体遮罩混合量",
            "min_value": "0",
            "max_value": "100",
            "default": "0",
            "step": 1,
            "help": "组合遮罩的混合距离。不适用于边框遮罩。",
        },
    },
}
